### ISSUE TITLE
In a certain case, Chrome will warn about a "performance issue" for the AdGuard extension.

### ISSUE THREAD

**Issue by kodiakhub** [AdguardTeam/AdguardBrowserExtension#2952] opened 2024-09-19 15:48 UTC
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.91

### Browser version

Chrome 129.0.6668.59

### OS version

Windows 10

### Ad Blocking

AdGuard Base filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Language-specific

AdGuard Turkish filter

### Issue Details

First of all, I tested it on a example site, maybe it is not easy here. But on heavier sites, it may be more obvious when you make changes to the filter rules etc.

Steps to reproduce:

1. Watch the video

### Expected Behavior

No extension error.

### Actual Behavior

Extension error.

### Video

<details><summary>Video</summary>

https://github.com/user-attachments/assets/0d3212fa-ddf4-464c-bcf5-e8e585634e10

</details>

**Comment by alexx7311** [comment] 2024-09-19 16:28
@kodiakhub, hello! The engine restarts every time you make changes, including times when you turn on and off the User rules. This is expected behaviour of Chrome browser and if you do that in 4.4 the result will be the same. More interestingly, you have an error displayed in the console related to the AdGuard Popups filter and I can't reproduce it yet. Do you have a way to reproduce it?

**Comment by alexx7311** [comment] 2024-09-23 10:00
@kodiakhub I still can't reproduce it. Anyways I'm closing this issue, but if the problem with AdGuard Popups filter is still relevant and you have exact steps on how to reproduce it, please create a new issue.

**Closed** 2024-09-23 10:01 UTC
Labels: Bug, Priority: P4, MV3
