### ISSUE TITLE
[Safari] Sometimes Adguard dialog window is blank

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdguardBrowserExtension#861] opened 2017-09-21 17:32 UTC
Hi,
I'm using Adguard adblock extension on Safari and sometimes Adguard dialog window is blank.

### Steps to reproduce
I'm unable to reproduce it, it seems to be random.

### Expected behavior
When you click on Adguard button, Adguard dialog window appears with its contents.

### Actual behavior
When you click on Adguard button, Adguard dialog window appears without any content.

<details><summary>Screenshot:</summary>

![adguard blank window](https://user-images.githubusercontent.com/1375223/30709610-25cc2e72-9f03-11e7-8135-4cc9e98c14f0.png)

</details>

### Your environment

* Adguard AdBlocker extension version: 2.6.5 (Content Blocking API)
* Environment name and version: Safari 11, macOS 10.12.6
* Filters you use in Adguard: default list
* Any other browser extensions you have installed: none

**Comment by zebrum** [comment] 2017-09-25 14:16
@superlex hello!
did you check on v2.6.7? 
there is also v2.7.2 will be released soon. 

I'll try to reproduce the issue on my side

**Comment by superlex** [comment] 2017-09-28 17:13
Thanks zebrum for your answer.
I have v2.6.5 because it's the only available on safari-extensions site. Do you know when the new v2.7.2 will be available there?
However I'll try with v2.7.2 from here too.

**Comment by zebrum** [comment] 2017-09-29 10:31
We've released the 2.7.2 actually! You can download it from our repo here: https://github.com/AdguardTeam/AdguardBrowserExtension/releases/download/v2.7.2/safari-release-2.7.2.safariextz and install manually

or wait a little until safari store will be updated.

**Comment by zebrum** [comment] 2017-10-05 12:43
randomly reprosucible 
1.
![screenshot 2017-10-05 15 37 56](https://user-images.githubusercontent.com/23637588/31227743-a74cae3c-a9e3-11e7-9916-018f69cd88a6.png)


2.
![screenshot 2017-10-05 15 39 38](https://user-images.githubusercontent.com/23637588/31227750-ad2ececa-a9e3-11e7-80ce-b6c64154a026.png)

**Comment by superlex** [comment] 2017-10-10 09:39
@zebrum 
Thank you!

**Comment by atropnikov** [comment] 2017-11-14 09:39
I tried many times, but I can't reproduce this issue. Errors in the browser console show that popup script can't access global variable `adguard` in the `safari.extension.globalPage.contentWindow`, but it must have access to the global page. It seems like a random browser bug and we need more details how to reproduce it.

**Comment by BlazDT** [comment] 2018-02-25 21:50
Reproduced on a fresh Safari installation on Windows and Extension 2.8.3. No errors in console though.

![safari](https://user-images.githubusercontent.com/34266271/36646901-3d41b102-1a7e-11e8-9cf0-ddf614daac2b.png)

**Comment by superlex** [comment] 2018-03-03 16:08
Now I'm using Safari 11.0.3 on macOS 10.13.3. With AdGuard 2.8.4 the bug seems fixed, but I'm waiting to confirm this.

**Comment by ameshkov** [comment] 2018-03-04 20:45
Thank you! Please reopen if it happens again

**Comment by superlex** [comment] 2018-03-08 15:56
Sorry, it happens again. 
![screen](https://user-images.githubusercontent.com/1375223/37160849-79ad04d6-22f1-11e8-9288-2ab57640747c.png)

AdGuard AdBlocker 2.8.4, Safari 11.0.3, macOS 10.13.3

**Comment by ameshkov** [comment] 2018-06-08 13:40
Closing as Safari extensions are deprecated in Safari 12, and in a new app this menu will look differently.

**Closed by ameshkov** 2018-06-08 13:40 UTC
Labels: Cannot Reproduce, Safari

**Comment by superlex** [comment] 2018-06-08 19:13
Ok, thanks.

**Comment by erkinalp** [comment] 2019-03-25 15:53
Not Safari specific. Also emerged on Firefox Quantum recently.
