### ISSUE TITLE
Adguard feature in Chrome developer tool not working on some websites. Is that blocked or bug❓

### ISSUE THREAD

**Issue by kodiakhub** [AdguardTeam/AdguardBrowserExtension#2203] opened 2022-10-02 16:50 UTC
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
Adguard Browser Extension 4.1.36
- **Browser and version:**
Google Chrome (64-bit) 106.0.5249.91
- **Operating system and version:**
Windows 10 21H2 (19044.2075)

### Expected Behavior

Adguard feature in Chrome developer tool is supposed to show element rules when clicking on elements on this website.

### Actual Behavior

Adguard feature in Chrome developer tool is not showing element rules when clicking on elements on this website.

### Video

<details><summary>Detail:</summary>

https://user-images.githubusercontent.com/56846906/193465465-698038ce-09fa-4811-818e-5f0510aba60c.mp4

</details>

### Additional Information

I've come across this issue on some websites and this issue before was mostly related to in-video player issues. This time, I felt the need to report it because it is related to website page. As end user, if this is user error, please let me know. Thanks in advance.

**Comment by maximtop** [comment] 2022-10-03 04:49
There is a known bug when chrome can't attach extensions to developer tools
https://bugs.chromium.org/p/chromium/issues/detail?id=1311690

But in your case, it seems to happen because this website prevents opening developer tools with debugger statements. When execution is stopped the AdGuard developer tools are not working as well. 
You may circumvent this debugger statement by pressing on deactivate breakpoints button as shown on the screenshot.
![image](https://user-images.githubusercontent.com/17272769/193503492-dbe813b5-19da-40f1-930a-ffa405d6a97c.png)

**Comment by Birbber** [comment] 2022-10-05 10:27
Closing this issue. Please re-open in case of additional questions.

**Closed** 2022-10-05 10:28 UTC
Labels: Question

**Comment by maximtop** [comment] 2022-10-10 09:46
It's by design. This tool uses a placeholder over the whole iframe. 
Use developer tools for better element selection.
If you would like to add some feature requests for it, you can do it here https://github.com/AdguardTeam/AdguardAssistant
