### ISSUE TITLE
Google Maps Broken

### ISSUE THREAD

**Issue by CrypticCus** [AdguardTeam/AdguardBrowserExtension#2396] opened 2023-07-10 20:46 UTC
### AdGuard Extension version

4.1.56

### Browser version

chrome 114.0.5735.199

### OS version

Windows 11 22621.1848

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter, EasyList, ABPindo, Fanboy's Anti-thirdparty Fonts, EasyList Cookie List, NoCoin Filter List, Frellwit's Swedish Filter, YousList

### What Stealth Mode options do you have enabled?

Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Disable WebRTC

### Issue Details

Google maps broken, can't search or create routes when ad blocking is enabled

### Expected Behavior

enable all filters, maps will be broken. disable adguard and it will work again.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

none

**Comment by alexx7311** [comment] 2023-07-12 16:32
Hello! We couldn't reproduce the problem. Do you have other browser extensions installed that may affect AdGuard? Is the problem recurring in a different browser or in the incognito mode of the Chrome browser?

Have you tried reinstalling the extension?
What steps do you take to reproduce the problem? Please attach some screenshots to illustrate the problem.

**Comment by CrypticCus** [comment] 2023-07-16 13:04
its working right now, because adguard and google maps build has been updated. we will see what happens in the future

**Comment by alexx7311** [comment] 2023-07-18 11:19
That's great! We'll close the issue for now. You can reopen the issue if the problem recurs.

**Closed** 2023-07-18 11:19 UTC
Labels: Bug, Priority: P4
