### ISSUE TITLE
Browser extension settings are reset after quitting Firefox

### ISSUE THREAD

**Issue by QueerestPunk** [AdguardTeam/AdguardBrowserExtension#2207] opened 2022-10-11 19:21 UTC
Every time I open up Firefox (after having quit it), nearly all of my AdGuard browser extension settings are changed, presumably reset to default settings. This issue started occurring 1-2 weeks ago.

### Changed settings include:
- Switching off nearly all filters
- Switching off "Stealth Mode"
- Switching on "Notify about extension updates" under "Additional settings"

### Steps:
**1.** Quit Firefox, and shut down Mac
**2.** Turn on Mac, and open Firefox with restored session
**3.** Most recently viewed restored window opens onto a new tab (see Screenshots below)

<details><summary>Screenshot 1</summary>
![Screen Shot 2022-10-11 at 11 27 52 AM](https://user-images.githubusercontent.com/112850484/195179978-0996b264-2b1a-44bf-b188-05b92784af54.png)
New tab opens, which briefly displays "Please wait while filters database is loading..."
</details>
<details><summary>Screenshot 2</summary>
![Screen Shot 2022-10-11 at 11 33 50 AM](https://user-images.githubusercontent.com/112850484/195179923-e80aacc5-7dbf-4d99-8fdd-8a7b3dfd884c.png)
The new tab loads to the URL "https://welcome.adguard.com/v2/thankyou.html," which displays "Configure AdGuard extension" with 4 toggles that are switched off
</details>

**4.** Go to extension settings, and see various toggles are changed to be switched on/off (presumably set back to default settings)
**5.** Some toggles reset themselves immediately after I switch them on/off, requiring 1-2 more clicks to 'stick'

### My environment:
* AdGuard browser extension: 4.1.37
* Firefox: 105.0.3
* macOS High Sierra: 10.13.6
* I also have other adblockers installed (uBlock Origin, AdBlocker Ultimate, and Ghostery), but they've never conflicted/interfered with each other

Thank you in advance to anyone who may know what the problem is!

**Comment by Aydinv13** [comment] 2022-10-12 10:28
@QueerestPunk your issue was transferred to the correct repo.

**Comment by Birbber** [comment] 2022-10-13 07:43
Looks like a duplicate of #2189. Will close this one.

**Closed** 2022-10-13 07:43 UTC

**Comment by QueerestPunk** [comment] 2022-10-13 16:09
> Looks like a duplicate of #2189. Will close this one.

Hi there, apologies for not noticing #2189! That page doesn't have a solution though, despite also being marked as 'closed.' Is this problem just a bug then that the AdGuard team will work on fixing?
