### ISSUE TITLE
AdGuard stops blocking ads due to missing the tab context

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#2438] opened 2023-08-15 13:33 UTC
### AdGuard Extension version

4.2.151

### Browser version

Chrome 115

### OS version

Windows 10 22H2

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Issue Details

AdGuard occasionally stops blocking ads. Reenabling AdGuard extension fixes the issue.

![Screenshot 2023-08-15 212820](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/142320869/681721b4-f479-4ac1-8bc3-58700ec359c5)

**Comment by maximtop** [comment] 2023-08-15 13:34
Do you have steps to reproduce?
Looks like a duplicate of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2433

**Comment by UnwrittenRule** [comment] 2023-08-15 13:41
I don't have the steps but I leave my browser and tabs in the background for a few hours/days and I come back to AdGuard not blocking ads on some sites. This has been happening since I updated to the latest version.

**Comment by ameshkov** [comment] 2023-08-16 11:35
Might be caused by the new memory saver feature of Chrome.

Can be tested on our side using chrome://discards/

**Comment by ameshkov** [comment] 2023-08-16 11:37
Actually, very easy to reproduce:

1. Open example.org
2. Go to chrome://discards/ and find `example.org`
3. Click "Urgent discard"
4. Get back to example.org and open the extension menu
5. You'll see exactly the same issue as in the original report

**Comment by Birbber** [comment] 2023-08-24 09:14
Closing as a duplicate of [#2433](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2433).

**Closed** 2023-08-24 09:15 UTC
Labels: Bug, Resolution: Duplicate, Status: Resolved, Priority: P2, Version: AdGuard v4.2.x (hotfix)
