### ISSUE TITLE
JS-rule doesn't work in Firefox extension

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdguardBrowserExtension#2147] opened 2022-07-28 22:49 UTC
`forbes.com#%#AG_onLoad(function(){if(!document.cookie.includes("cmapi_cookie_privacy")){var d=new MutationObserver(function(){var a=document.querySelector("#consent_blackbar"),b=document.querySelector("#consent_blackbar button#truste-consent-button");a&&b&&(d.disconnect(),a.style="display: none !important;",b.click())});d.observe(document,{childList:!0,subtree:!0}),setTimeout(function(){d.disconnect()},1E4)}});`

This rule doesn't work with Firefox extension (does not even show up in the filtering log), but it works in Firefox  with AG for Windows.

The issie in AdguardFilters:
https://github.com/AdguardTeam/AdguardFilters/issues/125231

**Comment by maximtop** [comment] 2022-07-29 04:38
I've added this rule to user rules and it seems to be working. Also I can see it in the filtering log.
<img width="1652" alt="image" src="https://user-images.githubusercontent.com/17272769/181683789-2ad16ad5-6a2c-4cff-ab19-59fa7ac69d53.png">

**Comment by gork7777** [comment] 2022-07-30 02:55
I can see the rule too. (Without add to user rules)
![image](https://user-images.githubusercontent.com/35523759/181867502-b8cc5000-b297-445a-834e-0b6aeb633746.png)

**Comment by Birbber** [comment] 2022-08-01 10:46
@Sergey-Lyapin Wasn't able to reproduce on my end as well. Will close this issue. Please re-open if needed.

**Closed by Birbber** 2022-08-01 10:46 UTC
