### ISSUE TITLE
Add static network filter option - 'permissions'

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdguardBrowserExtension#2408] opened 2023-07-20 15:41 UTC
### Issue Details

 - https://adguard.com/kb/general/ad-filtering/create-own-filters/#permissions-modifier
 - https://github.com/gorhill/uBlock/commit/5ebdbf3e24393560156fdcd931e31f901471f7f3

**Comment by maximtop** [comment] 2023-07-25 11:49
This is duplicate of https://github.com/AdguardTeam/tsurlfilter/issues/66

**Closed by maximtop** 2023-07-25 11:49 UTC
Labels: Feature Request, Priority: P4
