### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by JohnSheppard11** [AdguardTeam/AdguardBrowserExtension#2972] opened 2024-09-30 04:29 UTC
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.113

### Browser version

Google Chrome 129.0.6668.60

### OS version

windows 10 22H2 19045.4894

### Issue Details

Steps to reproduce:
1. Launch

5 browser windows, ~30-50 tabs each. PC Power - sleep only.

1+ week already...

Temp fix: Reopen tab, for some sites after reopening you need to close the remaining processes/scripts through the browser task manager.

### Expected Behavior

Working properly.

### Actual Behavior

Memory leak happens.
Why plz.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

This bug may also be present in other browsers, check.

(Memory leak in 2024 imagine)

Using since 2011.

**Comment by JohnSheppard11** [comment] 2024-10-03 06:07
Hello? Memory Leak ignore? Where fix? DO I NEED TO DELETE THIS EXTENTION AND BLACKLIST YOUR COMPANY? My eyes is bleeding from the ads, because I deactivated the extention, I will delete adguard ina few days and will try another adblockers. You know, you need to fix CRITICAL BUGS or you will lose the users.

**Comment by rpodric** [comment] 2024-10-04 06:08
Yes, it is present in other browsers: Slimjet, for example. That's an outdated browser to be sure, but at least it points away from Chrome. This never happened with the MV2 version.

**Comment by jimsinenomine** [comment] 2024-10-17 06:28
This has been present for the past several versions and still persists for 5.0.138.  A web page/tab that is open for a significant period of time and/or one that causes a lot of AdGuard extension blocking will cause an out of memory error.  I've seen it in Edge, Brave and Vivaldi.  I've had to stop using the extension and revert to uBOL in the meantime.

**Comment by jimsinenomine** [comment] 2024-10-26 13:52
Still present in 5.0.161

**Comment by rpodric** [comment] 2024-10-26 14:50
I guess no one has looked at it yet. Maybe this is the wrong way to report.

**Comment by windwak3r** [comment] 2024-10-28 10:33
@jimsinenomine @JohnSheppard11 @rpodric 
Please reproduce the problem and open Task Manager in Chrome (Shift + Esc). How much memory does AdGuard consume and what is the CPU load? Can you reproduce the problem consistently on certain websites or can it happen on any website?

> A web page/tab that is open for a significant period of time and/or one that causes a lot of AdGuard extension blocking will cause an out of memory error.

How long does the page have to be open? Do you just leave the page open or refresh it or click something on the page?  Do you have any memory-saving options enabled in your browser?

It would also be great if you attach your AdGuard extension settings in the comment.

**Comment by jimsinenomine** [comment] 2024-10-30 18:03
The ones it's happened on for me are "voice.google.com" and "mail.google.com".  I have them permanently open in Edge.  Settings are attached.  I've turned the extension back on and it should cause the error again (although I did notice an update to 5.0.162).  Assuming it errors, I'll then do the task manager checks and report back.

[adg_ext_settings_5.0.162_301024-125258.json](https://github.com/user-attachments/files/17577090/adg_ext_settings_5.0.162_301024-125258.json)

**Comment by rpodric** [comment] 2024-10-30 18:30
In my case, it must have been YouTube, if the site matters at all, which I'm guessing that it doesn't, since I don't use that browser for anything else. I think it's much more the time on a given site rather than the site.

**Comment by jimsinenomine** [comment] 2024-10-31 23:53
Here you go re the error and the task manager.  Not sure how much it helps.  There's a theme here - in case anyone didn't notice  🙂  i.e. Google-owned web sites (Voice, Gmail, YouTube, etc.).  Took 10-12 hours for this error to show up.  HTH.
![Edge OoM error](https://github.com/user-attachments/assets/b98ec31b-54c0-4121-8eb9-ab99d39ec2ad)
![Edge OoM - task manager](https://github.com/user-attachments/assets/62165313-bee5-4184-bdb2-057d103c7128)

**Comment by jimsinenomine** [comment] 2024-11-07 05:36
Issue remains in 5.0.164

**Comment by rpodric** [comment] 2024-11-07 05:43
I know there's a bit of a coincidence since all the sites mentioned so far relate to Google, so it may be instructive to try to replicate on some unrelated site, like Wikipedia or whatever else.

**Comment by scviktor** [comment] 2024-11-07 12:22
Can confirm the same behavior on Windows 11 with GoogleChrome 130.0.6723.92 and AddGuard Extension 5.0.164. The problem occurs after a few hours of inactivity on various websites such as: E.g. support.sap.com and others.

The tabs appear blank with an “Out of Memory” error message and a high memory usage of 1GB to 4GB. System memory of 40 GB RAM almost completely used. Closing tabs frees up storage space accordingly.
Disabling the AddGuard extension will completely resolve the issue.

**Comment by JohnSheppard11** [comment] 2024-11-10 22:17
Firstly, in 2024, allowing a memory leak to appear in the code is already too much, such a level of incompetence should no longer exist. Secondly, I don’t see the point in dumping anything, all open sites infinitely gain size in RAM after 30 minutes - 1 hour. I don’t know how and where to open the settings, you didn’t provide any instructions on what and where to click, and I, with 5 open windows and 200 tabs, have no desire to risk losing data and turn on your broken extension again to open some settings. If you are not able to write basic code elements, maybe you can find someone who can? Or you can just roll back your raw and useless update back to MV2, and rewrite entire code, and meanwhie I'll go look for alternatives. It sounds rude yes, but I have been using your extension for 10 years, I am very upset by such a slap in the face, I have been stuck with ads for 2 months already, and you have not even tried to roll back the update or give me a link to the previous version. I'll go look for alternatives, and you continue to do nothing with the critical bug.

**Comment by jimsinenomine** [comment] 2024-11-16 13:58
Not fixed in 5.0.167

**Comment by windwak3r** [comment] 2024-11-18 17:19
We are preparing a possible fix for this problem. Further discussions will take place at https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2594

**Closed** 2024-11-18 17:19 UTC
Labels: Bug, Priority: P4, MV3

**Comment by rpodric** [comment] 2024-11-18 17:38
Isn't that thread, a year old, about the MV2 version though? I never saw the problem with MV2.

**Comment by Tasiorsa** [comment] 2024-11-25 14:53
> We are preparing a possible fix for this problem. Further discussions will take place at #2594

This version is only for Chrome not for Firefox :-(

**Comment by maximtop** [comment] 2024-11-25 15:11
There will also be a fix for Firefox. It is currently under review.

**Comment by Tasiorsa** [comment] 2024-11-25 15:44
> There will also be a fix for Firefox. It is currently under review.

But for firefox still 4.41 version - not the latest 4.48

**Comment by maximtop** [comment] 2024-11-25 15:58
>But for firefox still 4.41 version - not the latest 4.48

The Firefox version of AdGuard AdBlocker (4.4.48) is currently under review in the Firefox Add-ons store.

**Comment by Tasiorsa** [comment] 2024-11-26 08:23
Firefox 132.0.2 - Adguard 4.48 and everything looks good after 24h :-) 
![{E6F1B7DE-4899-42E0-BB1F-F6D229E5FAD0}](https://github.com/user-attachments/assets/a953d6b0-4313-4977-b480-5ffdf5b4ba5a)
