### ISSUE TITLE
Cannot disable ad blocking in Tor Browser

### ISSUE THREAD

**Issue by suhan3z** [AdguardTeam/AdguardBrowserExtension#96] opened 2015-12-04 15:37 UTC
Disable filtration on page by checkbox, checkbox change state, but after refresh filtration continued.
Expected: filtration stops

**Comment by ameshkov** [comment] 2015-12-04 18:00
The problem is that getChannelContextData returns null in case of Tor Browser

**Comment by atropnikov** [comment] 2015-12-10 09:53
Fixed in https://github.com/AdguardTeam/AdguardBrowserExtension/issues/47

**Closed by atropnikov** 2015-12-10 09:53 UTC
Labels: Bug, Firefox
