### ISSUE TITLE
Remove tracking parameters don't work on Amazon.com

### ISSUE THREAD

**Issue by oldcastlehq** [AdguardTeam/AdguardBrowserExtension#1338] opened 2019-03-17 18:13 UTC
### Steps to reproduce

1. At AdGuard  Remove tracking parameters settings  I added `ref=`
2. Visit https://www.amazon.com/Bohemian-Rhapsody-Original-Soundtrack-Queen/dp/B07H1DW8SY/ref=sr_1_5?crid=1VDGKXLOUDI9Z&keywords=bohemian+rhapsody&qid=1552846121&s=gateway&sprefix=bohem%2Caps%2C500&sr=8-5

### Expected behavior
Get the URL https://www.amazon.com/Bohemian-Rhapsody-Original-Soundtrack-Queen/dp/B07H1DW8SY/

### Actual behavior
https://www.amazon.com/Bohemian-Rhapsody-Original-Soundtrack-Queen/dp/B07H1DW8SY/ref=sr_1_5?crid=1VDGKXLOUDI9Z&keywords=bohemian+rhapsody&qid=1552846121&s=gateway&sprefix=bohem%2Caps%2C500&sr=8-5

### Your environment
* AdGuard AdBlocker extension version: 3.0.8
* Environment name and version: Firefox on macOS
* Filters you use in AdGuard: Defaults
* Any other browser extensions you have installed: nope

**Comment by ameshkov** [comment] 2019-03-18 09:43
Basically, this is a duplicate of https://github.com/AdguardTeam/CoreLibs/issues/485

So we have a similar issue in other AdGuard products, inability to handle parameters with are parts of the URL. Once we figure a solution in CoreLibs repo, we'll migrate it to the browser extension.

**Closed by ameshkov** 2019-03-18 09:43 UTC
Labels: Duplicate
