### ISSUE TITLE
Youtube recognizes active Adblock and refuses to play any videos

### ISSUE THREAD

**Issue by LorenzWiedemar** [AdguardTeam/AdguardBrowserExtension#2653] opened 2023-12-17 11:39 UTC
### AdGuard Extension version

Version 4.2.228

### Browser version

Firefox 120.0.1

### OS version

Windows 10

### What filters do you have enabled?

AdGuard German filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, EasyList Italy, Dandelion Sprout's Nordic Filters

### Issue Details

Over a period of several weeks Google-Youtube informed me that the use of Adblocking Software was prohibited. Since I didn't react in any way they recently started to restrict me to watching only three three videos per day. Since I still didn't deactivate my Adblock add on they now deny me access to Youtube altogether.
However, when I use Brave Browser and sign into my Youtube account, there are no restrictions activ, despite Brave Browser too, blocking all the ads.

### Expected Behavior

For Years I was tolerant to the Ads which where presented to my on Youtube. During the last 11/2 years I noticed a sharp increase in duration and frequency these ads where presented. It reached a threshold where it became so anoying, that I decided to install Adblock. It worked extremly well and my experience on Youtube improved by a large ammount. I expect my Adblocker software to block ads but otherwise grant my access to the content. And if somehow possible I would like to stick with Firefox as my daily browser.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Birbber** [comment] 2023-12-22 11:58
Hello. Thank you for the report.
We already have [an open issue](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2532) on this matter. I'll close this one as a duplicate of #2532

**Closed by Birbber** 2023-12-22 11:58 UTC
Labels: Bug, Priority: P4
