### ISSUE TITLE
Misbehaviour of AdGuard externsion on Linux

### ISSUE THREAD

**Issue by mdziczkowski** [AdguardTeam/AdguardBrowserExtension#1855] opened 2021-09-11 07:28 UTC
**Enviromental informations:**

- **System**: Linux (64-bit)
- **Tested on Browsers**: Firefox 92, Tor Browser 10.5.5 (and newer)
- **AdGuard version**:  3.6.13

### Issue Details

1. After importing the earlier saved (using proper "export" buttons) settings, not every previously saved settings were restored, forcing me to set anything over again from the begining
2. After importing the rules and adding a new one, under the text area was whole time displayed the "saving..." text
3. The enabled filters become self disabled

Whenever I get able to take the screenshoot's, I'll include them

**Comment by Birbber** [comment] 2021-09-14 16:19
@mdziczkowski Hi!
What settings exactly were not restored? ("Stealth mode" settings aren't included during export in the release version)
Please give us more details on the issues and attach some screenshots.

**Comment by Birbber** [comment] 2021-09-21 10:59
@mdziczkowski Any news?

**Comment by mdziczkowski** [comment] 2021-09-22 11:49
In between 19 Sept and 16 Oct I&#39;m aboard and can&#39;t provide you with the requested informations, but I&#39;ll do that as soon as I get back.   I appologise if you haven&#39;t been notified thru the autoresponser.   With regards,  Mcgiwer
  
            
          
     
      
       
        Dnia 21 września 2021 13:00 Anna ***@***.***&gt; napisał(a):
       
    
       
         
 github.com @mdziczkowski  Any news?

**Comment by Birbber** [comment] 2021-09-22 11:57
@mdziczkowski Sure, we'll be waiting.

**Comment by Birbber** [comment] 2021-12-07 08:40
@mdziczkowski There's 4.0 beta version available, so you might want to try this out and see if the issue is still present.

**Comment by mdziczkowski** [comment] 2021-12-07 16:58
UPDATE:

I had checked the newest AdGuard and I got forced to open a new ticket with an found bug, with causes the sites to break, by (among other) to prevent from opening links in new tabs and/or after opening a new tab and pasting the link's URL into it, causing that this tab becomes closed

**Comment by Birbber** [comment] 2021-12-08 12:52
@mdziczkowski Could you send us a video recording, please? You can share it here or send to devteam@adguard.com.
I wasn't able to reproduce it so far.

**Comment by mdziczkowski** [comment] 2021-12-08 14:38
@Birbber Unfortunatelly that's impossible because it happens in miliseconds and my phone is unable to register (neither as photo nor video) so fast things

**Comment by Birbber** [comment] 2021-12-14 07:52
@mdziczkowski Will it be possible?

**Comment by mdziczkowski** [comment] 2021-12-14 11:14
> Also could you tell the new ticket number that you mentioned?

I had posted it directly to the developer, so it's not on GitHub

> @mdziczkowski How about some screen recording application? That would do the thing.

I use guest wise some one's computer and I'm not authorized to install anything on it. I hope you understand my situation

> If that's impossible give us the detailed steps to reproduce the issue, so we could follow it.

As mentioned in the ticket, AdBlock plugin for Firefox (called in short "**plugin**") causes immediatelly closing of new browser tabs when opening them from a link. This stop's when I stop or disable the plugin.

The strange thing is that earlier the plugin was working correctly. I'm not sure if the last update hasn't caused it.

**Comment by Birbber** [comment] 2021-12-15 10:34
@mdziczkowski Still unable to reproduce. 
Please try to reinstall the extension and set the settings manually (without import). If the webpages would still be closed as you explained, send us the links, so we could try the same.

**Comment by mdziczkowski** [comment] 2021-12-15 16:49
I was forced to uninstall the extension because it prevented me from normal website usage

**Comment by Birbber** [comment] 2021-12-17 08:32
Since we weren't able to reproduce the issue on our end, I'm closing it. Please re-open if needed.

**Closed** 2021-12-17 08:32 UTC
Labels: waiting for data
