### ISSUE TITLE
Ads are not blocked after few hours with Memory Saver

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardBrowserExtension#2371] opened 2023-05-31 17:55 UTC
### AdGuard Extension version

4.2.110 beta

### Browser version

Chrome v114.0.5735.91

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Issue Details

Ads are not blocked when Chrome's Memory Saver is turned on and after leaving any website (tab) with ads has been open for several hours (2-3 hours). Because the tab will auto refresh then **ads will reload again and AdGuard won't block them again**.
You can solve this problem only if you close the tab and open another tab.

### Steps to reproduce:

1. Open or enter any website with ads
2. Leave the tab open for a few hours and then look at the tab again (page will auto refresh). You can see that the ads are not blocked

### Expected Behavior

Ads (also Trackers, Socials, Annoyances and etc.) should be blocked when Chrome's Memory Saver is turned on and re-entering any website with ads that has been left open for 2-3 hours.

### Screenshots

<details><summary>Screenshot 1:</summary>

https://github.com/AdguardTeam/AdguardBrowserExtension/assets/35523759/c56b8eb1-23d3-45f2-b9d5-472dde31955f
</details>

<details><summary>Screenshot 2:</summary>

https://github.com/AdguardTeam/AdguardBrowserExtension/assets/35523759/d8f4bb2c-3e5c-4b3c-ba92-c708075cdcaa
</details>

### Additional Information

Here are example of websites with ads:

[Website 1](https://www.hurriyet.com.tr/gundem/selahattin-demirtas-aktif-politikayi-birakiyorum-42276555)
[Website 2](https://www.gazeteduvar.com.tr/natodan-kosovaya-700-baris-gucu-askeri-abdden-yaptirim-sinyali-haber-1621398)

**Comment by alexx7311** [comment] 2023-06-08 15:22
Hello! The problem will be fixed in the next beta version!

**Comment by gork7777** [comment] 2023-06-15 14:11
@alexx7311 Good to hear that, thanks.

**Comment by alexx7311** [comment] 2023-07-05 10:11
Hello! Please check if the problem is solved in this beta version at https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.2.133-beta

**Closed** 2023-07-14 09:13 UTC
Labels: Bug, Priority: P4
