### ISSUE TITLE
YouTube detected Ads Block 

### ISSUE THREAD

**Issue by jeeerice** [AdguardTeam/AdguardBrowserExtension#2630] opened 2023-12-05 05:44 UTC
### AdGuard Extension version

4.2.228

### Browser version

Chrome Version 119.0.6045.200 (Official Build) (64-bit)

### OS version

Windows 11

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

YouTube detects Ads blocker early Oct and seems like we had a release to fix it. https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.2.208

It was good for a month and now it happens again :(

### Expected Behavior

Expected to not get detected.

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/28407200/f800db02-c10c-4bf0-bd12-cb172343cc1b)

</details>

**Comment by Birbber** [comment] 2023-12-05 09:17
Hello! Thank you for the report. 
We already have [an open issue on this problem](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2532). I'll close this one as a duplicate of #2532.

**Closed by Birbber** 2023-12-05 09:17 UTC
Labels: Bug, Priority: P4
