### ISSUE TITLE
Disable auto-enabling of a specific language filter

### ISSUE THREAD

**Issue by trmdi** [AdguardTeam/AdguardBrowserExtension#2145] opened 2022-07-27 11:05 UTC
I'm using an external filter for the same language and I don't want the built-in one to be enabled automatically while still want that for other languages. The problem is the built-in one keeps being enabled whenever I disabled it.

**Comment by maximtop** [comment] 2022-07-27 11:23
Hi,
There is an option, which disables filters auto enabling.
![image](https://user-images.githubusercontent.com/17272769/181235263-fe37bd12-895f-4d5e-b672-63c2a0ccde66.png)

**Comment by trmdi** [comment] 2022-07-27 12:09
Wait, doesn't it also disable all other languages? I'm asking about disable just one language, while keeping it on for other ones.

**Comment by maximtop** [comment] 2022-07-27 12:29
It will disable filters auto enabling for all languages. There is no other possibilities to solve your problem. There are two ways auto-enable filters or no.

**Comment by trmdi** [comment] 2022-07-27 13:07
Could it work like this: by default, language-specific filters will be automatically activated like how it works currently, but once the user explicitly disables a language, it will never be automatically activated again.

**Comment by maximtop** [comment] 2022-07-27 13:28
It is possible. We will consider implementations of this feature.

**Comment by maximtop** [comment] 2022-07-27 13:30
Although it is not clear how to return filter to the state where you want it to be enabled again? What if some person accidentally or diliberately disabled filter and is not against filter to be enabled automatically?

**Comment by trmdi** [comment] 2022-07-27 13:41
I think that result requires quite a lot of actions, so it couldn't be an accident, and that user definitely know what he is doing and how to reenable it.

**Comment by maximtop** [comment] 2022-07-27 15:47
one action doesn't look like quite a lot of actions
but filters auto enabling for this filter would turn off implicitly and this may be a surprise for the user

**Comment by trmdi** [comment] 2022-07-27 16:17
> one action doesn't look like quite a lot of actions

To disable a language-specific filter, the user has to open Adguard settings (1) -> click on Filters (2) -> click on Language-specific (3) -> click on the Disable button to disable it (4). I mean this requires (4) steps, it can't be an accident.

>  but filters auto enabling for this filter would turn off implicitly and this may be a surprise for the user

sorry, I don't get this. Once the user disabled a filter, do you think he still wants to enable it automatically ?

**Comment by gork7777** [comment] 2022-07-27 16:28
@Stillness-2 @maximtop Well, a feature request like this has already been opened, maybe it will be included in the future. You can check this: [Disable unused language-specific filters](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2122)

**Comment by maximtop** [comment] 2022-07-27 17:14
@trmdi you are right

**Comment by maximtop** [comment] 2022-07-27 17:15
@gork7777 these features are not similar

**Comment by trmdi** [comment] 2023-04-28 09:22
Hi, any news on this FR ?

**Comment by maximtop** [comment] 2023-04-28 09:29
Hey @trmdi,

Just wanted to let you know that we haven't started working on this feature request yet since it's not a top priority right now. We know it matters to you and others, so we'll keep it on our radar for the future. Thanks for being patient with us!

**Comment by maximtop** [comment] 2023-09-11 16:22
Closing this issue, since it is a duplicate of this one https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2122

**Closed by maximtop** 2023-09-11 16:22 UTC
Labels: Feature Request, Priority: P4
