### ISSUE TITLE
Failed to load filters database on Kiwi Browser.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardBrowserExtension#1375] opened 2019-04-20 01:10 UTC
https://play.google.com/store/apps/details?id=com.kiwibrowser.browser

https://labs.xda-developers.com/store/app/com.kiwibrowser.browser

Kiwi is based on Chromium and WebKit.
Except for Firefox for Android, new Kiwi Browser also started to support extensions on Android.

1. Frozen on the page of initially loading filters database.
Can't enter the welcome page.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/FW6AcPS.png)
</details><br/>

2. After installation, it's blank in the section of filters.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/vAsadUK.png)
</details><br/>

@Arnaud
Which causes the issue?
Kiwi or AG?

**Comment by arnaud** [comment] 2019-04-20 07:44
The question is excellent although I don't feel very relevant to your issue :)

**Comment by superlex** [comment] 2019-04-20 11:59
@lancelot-moon 
did you try new "Phi" version?
AdGuard works well for me, only element picker is still bugged but the devolper is working very well and with ublock origin there are no problems for example :)

**Comment by ameshkov** [comment] 2019-04-20 12:26
> AdGuard works well for me, only element picker is still bugged

What exactly is the issue with the element picker?

**Comment by lancelot-moon** [comment] 2019-04-20 12:30
@superlex 

I surely use "Phi" version, which is the latest version on Google Play.
I just tried to reinstall it.
Still frozen on the page of initially loading filters database.
Can't enter the welcome page.

Where did you install extensions?
From chrome web store?

**Comment by ameshkov** [comment] 2019-04-20 12:31
@maximtop let's try to fix this in v3.1.

Hopefully, you'll be able to debug it via chrome://inspect

**Comment by superlex** [comment] 2019-04-20 14:40
@ameshkov 

> What exactly is the issue with the element picker?

It doesn't appear :p It goes to the site but nothing happens.
As regards AdGuard Assistant, sometimes works, sometimes doesn't (it doesn't recognize the site as valid).
![3](https://user-images.githubusercontent.com/1375223/56458639-8be1a100-6389-11e9-89e6-ada7f7b6f235.jpg)
![2](https://user-images.githubusercontent.com/1375223/56458640-900dbe80-6389-11e9-8b3b-b2f915996a15.jpg)

@lancelot-moon 

> Where did you install extensions?
> From chrome web store?

Yep, from chrome web store.
Do you always have the problem or only the first time?
![1](https://user-images.githubusercontent.com/1375223/56458692-4a052a80-638a-11e9-80b1-48e1b1900aa9.jpg)

However, I've problems editing my user filter, so with the editor.

**Comment by lancelot-moon** [comment] 2019-04-20 15:05
@superlex 

Always filters database are failed to be loaded.

**Comment by superlex** [comment] 2019-04-20 15:20
@lancelot-moon 
From Google Play Store, clean installation.

**Comment by maximtop** [comment] 2019-05-08 15:08
Seems that the first error is caused by this issue
https://github.com/kiwibrowser/android/issues/57
and the second error can't be reproduced in the current dev version
issue was in the class name specified in the HTML but absent in the CSS code, when i've removed it the problem was solved.

**Comment by maximtop** [comment] 2019-05-08 15:09
Also, I've found that kiwi browser, unfortunately, has been removed from the play store.

**Comment by lancelot-moon** [comment] 2019-05-08 15:12
Download from here.
https://labs.xda-developers.com/store/app/com.kiwibrowser.browser

**Comment by maximtop** [comment] 2019-05-08 15:20
> Download from here.
> https://labs.xda-developers.com/store/app/com.kiwibrowser.browser

I do not have difficulties to download it.
I've noted this in order to think about the necessity of spending time to support this browser or not.

**Comment by lancelot-moon** [comment] 2019-05-08 15:44
Have a good news.
Kiwi will be back to Google Play.
Simply wait.

**Comment by lancelot-moon** [comment] 2019-05-09 06:12
Kiwi is already back to Google Play.
https://play.google.com/store/apps/details?id=com.kiwibrowser.browser

Please solve the bug.
Thanks.

**Comment by kiwibrowser** [comment] 2019-05-11 22:51
Hi,

Should be fixed in https://storage.googleapis.com/kbdevreleases/Kiwi-20190510123933.apk
and we will check in the next week with Maxim what else to adapt (probably the prefs screen)

**Comment by kiwibrowser** [comment] 2019-05-13 10:27
Hello,

We've discussed with Maxim, he was very helpful and proactive. A couple of other fixes are getting prepared in Kiwi.

Stay tuned.

**Comment by superlex** [comment] 2019-05-13 14:32
Thank you very much :)

**Comment by kiwibrowser** [comment] 2019-05-15 12:40
Compatibility with events such as chrome.tabs.onCreated/onUpdated/onRemoved as been corrected in https://storage.googleapis.com/kbdevreleases/Kiwi-20190515123357.apk

I'm now reviewing the contextMenus part that AdGuard depends on.
Thanks for your patience,

**Comment by lancelot-moon** [comment] 2019-05-15 12:47
@kiwibrowser 
Where can I get full functions of KiWi?
I mean your APK downloading page, except for Google Play.

ex: NetGuard's APK files on GitHub and Google Play are different.

**Comment by kiwibrowser** [comment] 2019-05-15 12:49
https://discordapp.com/invite/XyMppQq - channel #updates - you get access to all dev builds.
Once builds are stable enough, they join GitHub releases page and Play Store.
Google Play and GitHub are the same, there is no reason to differentiate, since the browser supports extensions now.

**Comment by lancelot-moon** [comment] 2019-05-15 12:52
I supposed that Google asked you to remove some features. XD
Well, making different versions may trouble you.
I'll update from Google Play.
Thanks!

**Comment by superlex** [comment] 2019-05-20 10:49
Thank you :)

@lancelot-moon 
Is this bug fixed for you, with new Centaurus version?

**Comment by lancelot-moon** [comment] 2019-05-20 10:51
Fixed, but it's hard to configure settings.
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1400

**Closed** 2019-06-10 12:21 UTC
Labels: Bug, Compatibility, P3: Medium
