### ISSUE TITLE
The extension prevents localhost page from opening

### ISSUE THREAD

**Issue by eimarinin** [AdguardTeam/AdguardBrowserExtension#2850] opened 2024-06-20 10:13 UTC
using localhost, the ad blocker prevents the page from loading. the site is loading, but it shows a white page

**Comment by alexx7311** [comment] 2024-06-25 10:53
@eimarinin Hello! Please describe step by step how to reproduce the problem. Have you tried turning off Stealth module? Does the problem reproduce with Base filter enabled only or without any enabled filters?

**Comment by alexx7311** [comment] 2024-07-01 08:52
@eimarinin Any updates?

**Comment by alexx7311** [comment] 2024-07-15 08:49
@eimarinin We couldn't reproduce the problem. We'll close the issue for now, you can leave a comment if it's still relevant.

**Closed** 2024-07-15 08:49 UTC
Labels: Priority: P4
