### ISSUE TITLE
Youtube displays a pop up "Ad blockers are not allowed on YouTube"

### ISSUE THREAD

**Issue by Kugankr** [AdguardTeam/AdguardBrowserExtension#2542] opened 2023-10-15 11:11 UTC
### AdGuard Extension version

1.11.15 

### Browser version

Safari Browser

### OS version

Mac OS Ventura 13.3

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Block trackers

### Issue Details

The website Youtube.com displays a pop up message displaying "Ad blockers are not allowed on YouTube" on the safari browser on Mac OS Ventura 13.3 with the adguard extension 1.11.15 it instruct us to allow ads on YouTube.com
<img width="784" alt="Screenshot 2023-10-15 at 4 19 45 PM" src="https://github.com/AdguardTeam/AdguardBrowserExtension/assets/122229279/3f265f82-e9de-4dd6-8ea0-a17f33b6d9c2">

### Expected Behavior

The expected behaviour is not to show any pop ups or any dialogue box should be displayed .

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
<img width="784" alt="Screenshot 2023-10-15 at 4 19 45 PM" src="https://github.com/AdguardTeam/AdguardBrowserExtension/assets/122229279/9f6681b0-7e44-4485-a8de-039a2b4e57dd">

**Comment by flyingbug2** [comment] 2023-10-15 13:15
Microsoft Edge has the same problem.

**Comment by AkramiPro** [comment] 2023-10-15 22:02
for now after watch 3 video the playback is block permanently 

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/54323929/a3c7c0e5-9563-4066-92d3-57f7589e347c)

**Comment by Birbber** [comment] 2023-10-16 15:57
@Kugankr Hello! We're already working on this issue both for AdGuard for Safari and AdGuard Browser Extension. 
AdGuard for Safari has [its own repository](https://github.com/AdguardTeam/AdGuardForSafari).
I'll close this issue as a duplicate of [#913](https://github.com/AdguardTeam/AdGuardForSafari/issues/913). Stay tuned for updates.

**Closed by Birbber** 2023-10-16 15:57 UTC
Labels: Bug, Priority: P4
