### ISSUE TITLE
Firefox Nightly lists Adguard as a Legacy extension due to Embedded WebExtensions

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardBrowserExtension#682] opened 2017-05-10 08:59 UTC

**Comment by BooBerry** [comment] 2017-05-10 14:36
Fortunately you guys have some time before this becomes an issue with Firefox 57.

It's an Embedded WebExtension because of the migration of the data from the older extension to the WebExtension, right? If so, then this likely the best course of action for the time being.

Let 2.6 go stable, upgrade the majority of Firefox extension users to 2.6 and migrate their data over to the WebExtension. Then a few months later release the next version that is a full WebExtension.

The key here is to get that later, full WebExtension version of the Firefox browser extension finalized _**before**_ the release of Firefox 57 to the stable channel on AMO so users won't be left upgraded to Firefox 57 with a disabled Embedded WebExtension.

**Comment by ameshkov** [comment] 2017-05-23 08:32
> The key here is to get that later, full WebExtension version of the Firefox browser extension finalized and stable before the release of Firefox 57 on AMO

That'd be hard, review queue is astonishing at the moment. Never seen it that big ever.

**Comment by bkrcrc** [comment] 2017-07-14 18:07
Firefox Nightly 56 still has the problem. Drop-down menu not working.
See: http://prntscr.com/fvqze2

I opened options from right-click menu and here it is:
See: https://prnt.sc/fvr02n

**Comment by yfdyh000** [comment] 2017-07-14 22:56
@bkrcrc Try `extensions.webextensions.remote` to false.
May be https://bugzilla.mozilla.org/show_bug.cgi?id=1379508.

**Comment by BooBerry** [comment] 2017-08-12 18:47
Probably time to start thinking about pushing a pure WebExtension version to AMO.

https://news.ycombinator.com/item?id=14982884

Legacy WebExtensions (including hybrid WebExtensions), by default, are all now disabled in the latest Nightly build unless you set `extensions.legacy.enabled` to `true`.

**Comment by ameshkov** [comment] 2017-08-13 12:45
Sure, the next update will be a pure WebExtension, 99% users will migrate to 2.6.7 by that time.

**Comment by BooBerry** [comment] 2017-08-13 12:46
Any idea what the current percentage of users migrated to 2.6.7 is at right now?

**Comment by ameshkov** [comment] 2017-08-13 12:53
85% according to AMO stats

**Comment by BooBerry** [comment] 2017-08-13 12:56
Actually, that's not bad at all.

**Comment by ameshkov** [comment] 2017-08-13 12:59
Not bad indeed, but it will take quite some time to reach the 99%.

Meanwhile, I guess we should push the pure WE build to the dev channel.

**Comment by BooBerry** [comment] 2017-08-13 13:01
Pretty good idea, that's what @gorhill did with uBO.

**Comment by bkrcrc** [comment] 2017-08-13 13:20
Thanks for the Full-WE for us.
Recently, Nightly completely blocks the Legacy add-ons, even it offers me alternatives instead of them.
See: http://prntscr.com/g7x4i0

**Comment by BooBerry** [comment] 2017-08-13 13:22
Yeah, it's well known. You can force enable legacy extensions in Nightly by going to `about:config` and setting `extensions.legacy.enabled` to `true`. That'll get it working in the meantime until there's an update to the dev channel with the pure WE.

**Comment by ameshkov** [comment] 2017-08-16 15:59
Duplicate of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/819

We'll upload pure WE build to the beta channel tomorrow.

**Closed by ameshkov** 2017-08-16 15:59 UTC
Labels: Duplicate
