### ISSUE TITLE
Cannot scroll down in some website

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdguardBrowserExtension#2060] opened 2022-05-03 17:28 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 4.0.161
- **Browser and version:**
  - Mozilla Firefox Dev 101.0b1
- **Operating system and version:**
  - Ubuntu 22.04
- **Filters you use in AdGuard:**
  - List-KR, AG Tracking, AG URL, AG Social, AG Annoyances and **Fanboy's Annoyances**
- **Stealth Mode settings:**
  - None
- **Other browser extensions:**
  - KeePassXC

### Expected Behavior

Can scroll down

### Actual Behavior

Cannot scroll down

### Screenshots

<details><summary>Screenshot:</summary>

[Screencast from 2022-05-03 04:47:52 PM.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/8612426/Screencast.from.2022-05-03.04.47.52.PM.zip)

https://listauthorschat.slack.com/files/U032VH6S04F/F03EA1E9RQ9/screencast_from_2022-05-03_04_47_52_pm.webm

</details>

### Additional Information

- https://github.com/AdguardTeam/AdguardFilters/issues/117340
- https://listauthorschat.slack.com/archives/C010N14G4TF/p1651570477097619

**Comment by maximtop** [comment] 2022-05-04 05:50
Seems like the problem is in the Fanboy's Annoyances filter. 
If you disable it, you will be able to scroll the website.
I'm closing this issue as it should be resolved on the side of the filters.

**Closed by maximtop** 2022-05-04 05:50 UTC

**Comment by ryanbr** [comment] 2022-05-04 06:09
The issue doesn't present itself in uBO which is why a issue was logged here @maximtop

**Comment by AdamWr** [comment] 2022-05-04 06:29
If I'm not wrong, it doesn't happen with uBO, because the rule - `##.show-top-button` is not applied.
As far as I understand, it's probably related to this - https://github.com/uBlockOrigin/uBlock-issues/issues/1692 - generic cosmetic rules are not applied to body/html tag, and also due to this exception - `@@||tistory.com^$generichide`.
The same issue occurs with Adblock Plus.

**Comment by maximtop** [comment] 2022-05-04 07:29
Seems that you are right. We already have the issue not blocking body/html tag here https://github.com/AdguardTeam/tsurlfilter/issues/32
