### ISSUE TITLE
Safari (MacOS Sierra GM) : personal filters are not working

### ISSUE THREAD

**Issue by 1Claude** [AdguardTeam/AdguardBrowserExtension#359] opened 2016-09-09 23:07 UTC
On MacOS Sierra GM, the personal filters are not working. Old ones and new ones. 

At first, the new filters seems to work. But when coming back to the same web site where you blocked something, it shows again anyway. 

The old personal filters just don't work anymore.

**Comment by ameshkov** [comment] 2016-09-12 11:23
@1Claude hi! cannot confirm it on my side.

Please answer a few questions:
1. What exact version of Adguard do you use? Beta or stable?
2. Which filters do you have enabled in Adguard?

**Comment by 1Claude** [comment] 2016-09-12 18:42
Go to this web site : http://www.macg.co

In the middle, you'll see and ad with 3 squares, vertically. 

Block each of them.

Quit Safari.

Come back to the same web site.

Result : the ads you  blocked earlier are not now.

I tried with Adguard Browser extension 2.39 from the Safari extensions page. Also tried with the latest version 2.4.1.0 Safari from MacOS Sierra GM.

**Comment by ameshkov** [comment] 2016-09-13 16:25
Here is what I see, is that it?
https://monosnap.com/file/kMBjdI31U7YqJqQrcxobxULi0Maj8W

**Comment by 1Claude** [comment] 2016-09-13 17:55
That's one above.

But also bellow. 3 squares, vertically.

And above the 3 quares, there's also an add for some store.

See here : https://www.evernote.com/l/AAX_nko9SZNByYWfgwdJQJ6n4gcalUheR4Q

**Comment by ameshkov** [comment] 2016-09-13 21:23
What if you add this rule to your user filter manually:
`macg.co###block-block-16`

Does it help?

**Comment by 1Claude** [comment] 2016-09-13 21:31
No, sorry.

Like I said, all my personal filters are not working with Safari in MacOS Sierra. 

Here's the list I have for this particular web site : 

macg.co###block-block-15 > DIV.content > SECTION.refurb
macg.co###block-block-16 > DIV.content > DIV.couverture:last-child > A > IMG
macg.co###block-block-16
macg.co###block-block-14
macg.co###block-macg-stacksocial-widget-stacksocial
macg.co##A:nth-child(6) > IMG

I tried other adblockers. AdBlock Plus failed too. The only one that worked and kept my personnal filters in MacOS Sierra with Safari is plain Adblock. But I prefer AdGuard.  :-)

**Comment by ameshkov** [comment] 2016-09-15 12:55
The only idea I have is that you have too many filters turned on and all filter rules above 50k are ignored.

What exact filters do you have enabled?

**Comment by 1Claude** [comment] 2016-09-15 18:08
I don't know, but this does not happen in MacOS El Capitan. 

And I haven't touch anything or add more filters.

**Comment by 1Claude** [comment] 2016-09-15 22:01
I just installed the latest MacOS Sierra GM (build 16A323)

If I reload the page, then Adguard works. The personnal rules filters apply.

**Comment by ameshkov** [comment] 2016-09-16 10:29
Huh, finally I got what's wrong.

It seems that in Safari 10.0 this bug is returned:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/153

I'll alert Safari Content Blocker dev about it, I hope they'll fix it soon.

**Comment by ameshkov** [comment] 2016-09-16 11:00
New bug report:
https://bugs.webkit.org/show_bug.cgi?id=162057

Also I've sent an email directly to Alex Christensen, let's hope he'll fix this issue as soon as possible.

Closing this issue as a duplicate of #153 .

**Closed by ameshkov** 2016-09-16 11:00 UTC
Labels: Duplicate, Question, Safari

**Comment by ameshkov** [comment] 2016-09-16 11:01
Also thank you for reporting this issue and for your patience:)
