### ISSUE TITLE
Give us an option to add 3rd party filters with their URLs

### ISSUE THREAD

**Issue by bkrucarci** [AdguardTeam/AdguardBrowserExtension#412] opened 2016-10-20 14:26 UTC
Can we please get a feature like this in Adguard extension?
Please see: https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web#import-external-filter-lists

Thanks

**Comment by ameshkov** [comment] 2016-10-21 13:37
We'll do it along with planned add-on redesign.

**Comment by bkrcrc** [comment] 2016-10-21 13:42
Thanks @ameshkov

**Comment by ameshkov** [comment] 2018-06-08 13:31
Duplicate of #808 , done in the v3.0 branch

**Closed by ameshkov** 2018-06-08 13:31 UTC
Labels: Feature Request, P3: Medium
