### ISSUE TITLE
Extension stopped working on its own.

### ISSUE THREAD

**Issue by sh2sg** [AdguardTeam/AdguardBrowserExtension#2898] opened 2024-08-11 09:09 UTC
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

5.0.5

### Browser version

Chrome 127.0.6533.100

### OS version

Windows 11 23H2

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Language-specific

AdGuard Chinese filter

### Issue Details

Don't know how to reproduce it, the extension suddenly stopped working. It didn't filter anything, and clicking the icon showed an empty page.

Restarting Chrome didn't fix the problem.

Removing and reinstalling the extension solved it.

### Expected Behavior

Filter ads.

### Actual Behavior

stopped working.

### Screenshots

<details><summary>Screenshot 1</summary>

![image](https://github.com/user-attachments/assets/ae82661f-ca60-488f-a42c-8368325f9c2e)

</details>

**Comment by krystian3w** [comment] 2024-08-12 09:21
Maybe other MV3 add-ons They've run out limit of DNR rules.

It's definitely a good idea to disable other content blockers like:

- uBo **Lite** (MV3)
- AdBlock (latest version is in MV3)
- Adblock Plus 4.x (MV3 if downloaded from Chrome Web Store)

---

It is possible that the service worker has fallen asleep for good and hence the content is not blocked or hidden.

**Comment by alexx7311** [comment] 2024-08-12 09:53
@sh2sg, hello! For some reason the filtering engine doesn't start. If the problem is still relevant please do the following:
1. Go to `chrome://extensions/` and enable `Developer mode`
2. Find the AdGuard extension on the page and click `service worker`
3. Open the `Console` tab
4. Open the context menu and click `Save as…`
5. Attach the resulting file to a comment here

**Comment by krystian3w** [comment] 2024-08-13 06:30
Generate log almost never repair something itself.

**Comment by k6G52m4Dz75W** [comment] 2024-08-14 15:20
I think it is not a bug. It was quite possible that malicious site uses javascript or other stuff to disable adguard on purpose. Please add protection to the settings or the extention becomes totally useless and annoying.

**Comment by alexx7311** [comment] 2024-08-23 16:35
@sh2sg It could be a bug but we would need exact steps to reproduce it. We'll close the issue for now.
If the issue is still relevant please leave a comment.

**Closed** 2024-08-23 16:35 UTC
Labels: Bug, Priority: P4, MV3
