### ISSUE TITLE
Ad blocking filters constantly have to be re-enabled

### ISSUE THREAD

**Issue by kentuckywoman2** [AdguardTeam/AdguardBrowserExtension#2789] opened 2024-04-16 19:18 UTC
### AdGuard Extension version

4.3.35

### Browser version

Firefox 124.0.2 64-bit

### OS version

Windows 10 version 22H2 for x-64 based systems

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

The AdGuard Base filter automatically turns off. I have to constantly turn it back on. I also have "Activate the most appropriate filters automatically" enabled, although I'm not sure why that should make a difference. But when I check the filters, it always says there are no filters enabled, and then I have to enable it all over again. It's tiresome. But otherwise, the app won't block anything. When it stops showing ads blocked, I always know that adguard base filter has been disabled again. Sure would be nice if you could fix it. I never used to have a problem with Adguard.

### Expected Behavior

I expect that once I enable a filter, it will remain enabled unless I manually disable it. However, the Adguard Base filter is constantly being disabled, but not manually. I'm the only one who uses this computer. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

As above, the only guess I could make is that the "activate appropriate filters" is not working properly. But that's just a guess; I have no idea what's wrong but something is "buggy".

**Comment by alexx7311** [comment] 2024-04-17 15:54
@kentuckywoman2 Hello! This is most likely caused by a [bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1885297).

Please do the following:
1) Open the Browser console (press Ctrl + Shift + J (or Cmd + Shift + J on a Mac))
2) Choose Multiprocess mode and leave the Browser console opened
<details>
  <summary>Multiprocess mode</summary>

  ![Multiprocess mode](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/114913601/aa00993e-6eb2-4a8f-8e65-1bb1b1408ba2)

</details>

3) Follow steps 1-3 from this [instruction](https://maximtop.notion.site/How-to-export-logs-from-the-background-page-in-the-extension-fb7e2fe23cb0451ea010672ce0570929) for Firefox to open background page in the extension (go to `about:addons` > `Debug Add-ons` > `Inspect`)
4) Type each of these commands one at a time in the console of the background page and press Enter after each one:

`await browser.storage.local.get('adguard-settings');`

`await browser.storage.local.get('adguard-settings-2');`

`await browser.storage.local.set({'adguard-settings': 'test'});`

`await browser.storage.local.set({'adguard-settings-2': 'test'});`

`await browser.storage.local.remove('adguard-settings');`

`await browser.storage.local.remove('adguard-settings-2');`

5) Right click on any entry in console of the background page and click "Save All Messages to File" (as per step 4 in the [instruction above](https://maximtop.notion.site/How-to-export-logs-from-the-background-page-in-the-extension-fb7e2fe23cb0451ea010672ce0570929))
6) Go to https://firefox-storage-test.glitch.me/ and **save the content of this page** to a txt file.
7) Go to the Events tab in Firefox at `about:telemetry#events-tab`
8) Type in "Find in Events" field "extensions.data" and take a screenshot, then "storageLocalError" and take a screenshot.

<details>
  <summary>Find in Events</summary>

  ![Find in Events](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/114913601/e488439d-4440-45db-bf8f-4f0156d763d9)

</details>

9) Navigate to the Browser console (from the step 1) and right click on any entry and click "Save All Messages to File".
10) Please attach all resulting files to a comment in this issue https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775.

Thank you in advance for your help!

**Comment by alexx7311** [comment] 2024-04-17 15:56
@kentuckywoman2 We're closing this issue, you can leave a comment in https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775

**Closed** 2024-04-17 15:57 UTC
Labels: Bug, Priority: P4
