### ISSUE TITLE
Adguard breaks refresh in Safari Technology Preview

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#213] opened 2016-03-30 19:39 UTC
User report:
https://twitter.com/codehawkfalcon/status/715252854777384961

https://developer.apple.com/safari/technology-preview/

**Comment by ameshkov** [comment] 2016-03-30 19:49
Cannot reproduce it on apple.com and google.com, page refresh works as it should.

**Comment by hawkfalcon** [comment] 2016-03-30 20:02
I'm trying to find a way to reliably reproduce the bug. Things I know:
- It didn't show any images upon refresh of a page
- It would redirect to about:blank on refresh or link click sometimes (I'm trying to reproduce, it happened quite a few times)

**Comment by hawkfalcon** [comment] 2016-03-30 20:03
Just discovered the former bug occurs only on fresh install of extension, restarting browser after installation seems to fix. (completely uninstall + redownload, not disable)

**Comment by hawkfalcon** [comment] 2016-03-30 20:11
I can reproduce one bug reliably (though this seems to be a different bug):
- Completely remove extension
- Download from safari extensions
- Enable 
<img width="1027" alt="9ucnhn1" src="https://cloud.githubusercontent.com/assets/1509618/14155853/6c9b362a-f678-11e5-9207-641682b1ebfa.png"> and possibly disable acceptable ads

This occurs (all pictures vanish):
![lsy0a7u](https://cloud.githubusercontent.com/assets/1509618/14155971/ea5106f8-f678-11e5-83ae-6f404ae87671.png)

Still trying to reproduce the about:blank thing..

**Comment by hawkfalcon** [comment] 2016-03-30 20:17
That bug does not occur in normal safari. Just tried. 

I can't seem to reproduce the about:blank bug. I assumed it was this, because it started after I installed the extension, but perhaps it was something since fixed on apple's end. 

I'll let you know if I do find it again, but in the meantime the above is a different fun bug.

**Comment by ameshkov** [comment] 2016-03-30 20:18
And what about twitter bug? Do you have twitter broken all the time or until first refresh?

**Comment by hawkfalcon** [comment] 2016-03-30 20:20
It continues to be broken permanently.

**Comment by ameshkov** [comment] 2016-03-30 20:47
I've managed to reproduce it. Images are broken right after extension installation.

**Comment by ameshkov** [comment] 2016-03-30 21:45
Right after extension installation I see that Safari goes mad blocking all twitter images.
```
Content blocker prevented frame displaying https://twitter.com/wylsacom from loading a resource from https://pbs.twimg.com/media/CeyCG0EWIAAs908.jpg:thumb
```

There are no rules like that in AG filters, so I don't understand yet why does it happen.
Everything gets back to normal after browser restart.

**Comment by rltbennett** [comment] 2016-04-23 01:11
With Adguard enabled, I also frequently encounter the about:blank page. Also many pages do not have resources loaded (for instance Stackoverflow only loads raw HTML, no CSS). This occurs seemingly randomly, not exclusively when refreshing the page. However, this only occurs when using the new content blocking API. When using the old adblock method, nothing is broken.

This occurs in Technology Preview, not regular Safari.

**Closed** 2018-03-29 13:45 UTC
Labels: Bug, Safari
