### ISSUE TITLE
Adguard breaks Okta SSO signins to Zoom 

### ISSUE THREAD

**Issue by thinkbrown** [AdguardTeam/AdguardBrowserExtension#2652] opened 2023-12-15 18:54 UTC
### AdGuard Extension version

4.2.228

### Browser version

Firefox 120.0.1

### OS version

Fedora release 38

### What filters do you have enabled?

AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Widgets filter, Filter unblocking search ads and self-promotion

### Issue Details

Attempting to sign into a corporate zoom tenant via Okta SSO fails and causes a reload loop. The SAML exchange succeeds in the Okta logs, but the login doesn't complete.

### Expected Behavior

The login should be allowed to proceed.

### Additional Information

Adding `@@||zoom.us^$cookies` to user rules does not resolve the issue, but `@@||zoom.us^$document` does and logins proceed as usual.

**Comment by alexx7311** [comment] 2023-12-27 13:58
@thinkbrown Hello! It is possible that the problem is related to the document.referrer issue. As soon as the fix is in the release build, you can check on it, but for now you can use `@@||zoom.us^$document` if it helps you.

**Comment by alexx7311** [comment] 2024-03-14 11:05
@thinkbrown Please update the extension to the latest version and see if the problem persists.

**Comment by alexx7311** [comment] 2024-03-20 10:18
We'll close the issue for now. Please respond in this issue if the problem still persists.

**Closed** 2024-03-20 10:19 UTC
Labels: Bug, Priority: P4
