### ISSUE TITLE
No User Rules or Filters

### ISSUE THREAD

**Issue by BrokenShoeLace** [AdguardTeam/AdguardBrowserExtension#2027] opened 2022-03-27 00:09 UTC
Version: 4.0.141 extension
Windows: 11 Pro
Firefox: 98.0.2

Automatic installation of the above version has wiped all user and allow rules. All filters were disabled by default. Have manually activated them and updated to the latest rules but will need to begin my user list again.

**Comment by maximtop** [comment] 2022-03-28 05:12
Can you check if there are some errors during the update on the extension background page and send them to us here or to devteam@adguard.com?

Here is the instruction on how to view logs https://maximtop.notion.site/How-to-find-an-extension-logs-in-the-Firefox-682216c6dea54b6a9832edf924b07d3b.

**Comment by BrokenShoeLace** [comment] 2022-03-28 06:48
Hi,

Firefox Dev Tools say there is an XML parsing error in background.html (stray start tag "script").

`<!doctype html><html><head><meta charset="[UTF-8]()"></head></html><script src="[../pages/background.js](view-source:moz-extension://7bc56eb1-bff8-4a3c-9331-ab87d9a159f8/pages/background.js)"></script>`

![adguard-error1](https://user-images.githubusercontent.com/65475317/160340814-970c537d-877a-49e8-ad57-5cfca8d7116f.jpg)

![adguard-error2](https://user-images.githubusercontent.com/65475317/160341171-91981107-ecbb-4fd1-abd4-2875364b77c7.jpg)

![adguard-error3](https://user-images.githubusercontent.com/65475317/160341455-aa54aa79-11e9-4e25-a989-e5370c2ab571.jpg)

Cheers!

**Comment by maximtop** [comment] 2022-03-28 07:05
It's a known firefox bug, but not our culprit. Seems like you reloaded the browser and all logs wiped.

**Comment by BrokenShoeLace** [comment] 2022-03-28 07:31
Oh yeah, I remember the bug in Firefox from a few years back. They said before Firefox 77, it was fixed.

No, I have never reloaded it and I let it install itself on its own, thenalerts me.

**Comment by maximtop** [comment] 2022-03-28 08:34
Maybe you have a copy of your previous settings? If you send them to us we try to reproduce the issue? You can send them via devteam@adguard.com.

**Comment by maximtop** [comment] 2022-04-21 08:01
Closing this as not able to reproduce. If new details found feel free to open this issue again

**Closed** 2022-04-21 08:01 UTC
Labels: Resolution: Cannot Reproduce, Status: Resolved, Version: AdGuard v4.1
