### ISSUE TITLE
Adguard blocks access to gmail

### ISSUE THREAD

**Issue by hlvrn** [AdguardTeam/AdguardBrowserExtension#3053] opened 2024-11-27 22:02 UTC
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

Version 4.4.48

### Browser version

Microsoft Edge Version 131.0.2903.51 

### OS version

Windows 11

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter

### Security

Online Malicious URL Blocklist

### Issue Details

Steps to reproduce:
1. With Adguard enabled, trying to access gmail fails nearly all the time. Error message "ERR_TOO_MANY_REDIRECTS".
2. With it disabled, accessing gmail works.

### Actual Behavior

Can't access gmail. Error message "ERR_TOO_MANY_REDIRECTS".

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by windwak3r** [comment] 2024-11-29 10:54
@hlvrn, hello! I couldn't reproduce the problem. Please update filters in the extension, clear your browser cookies and check if the problem persists. 

Do you have any other extensions/apps installed that do network filtering? Please try to disable them too.

**Comment by windwak3r** [comment] 2024-12-03 08:40
@hlvrn any updates?

**Comment by windwak3r** [comment] 2024-12-09 10:28
We'll close the issue for now. Please leave a comment if the problem is still relevant.

**Closed** 2024-12-09 10:28 UTC
Labels: Bug, Waiting for data, Priority: P4, MV2
