### ISSUE TITLE
Invert whitelist mode confusing description of the feature

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardBrowserExtension#204] opened 2016-03-23 14:51 UTC
I'm not sure if this is intentional or not, but if it is, I think the UI text on the settings page should be made clearer. The description for the invert whitelist option is "Unblock ads everywhere except the whitelist", which made me think that no ad filtering would be applied at all to sites not on the whitelist. If the behavior is intentional, the text should be something like "Unblock ads everywhere except the whitelist, apart from ads which are included in your filter rules."

FKM-799-53501

**Comment by ameshkov** [comment] 2016-03-23 14:58
I didn't get it:)

> which made me think that no ad filtering would be applied at all to sites not on the whitelist.

That's exactly how this feature works.

> If the behavior is intentional, the text should be something like "Unblock ads everywhere except the whitelist, apart from ads which are included in your filter rules."

Hm, what does that mean? Is it about user filter?

**Comment by evgeniy-ADG** [comment] 2016-03-23 15:08
Yes, it's about user filter. User filter rules should be omitted too when using inverted mode.

**Comment by ameshkov** [comment] 2016-03-25 11:16
> But, due to what the description states, the element I hide should be unblocked

Yeah, it should. What browser does user use?

I've just checked in Chrome and it works as intended..

**Closed** 2018-06-08 12:16 UTC
Labels: Enhancement
