### ISSUE TITLE
AdGuard is deactivated every time Firefox is restarted

### ISSUE THREAD

**Issue by Skywriter960** [AdguardTeam/AdguardBrowserExtension#2771] opened 2024-03-30 14:33 UTC
### AdGuard Extension version

Version 4.3.35

### Browser version

Firefox 124.0.1

### OS version

Win 11

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

For whatever reason, AdGuard is deactivated 'by magic' the next time Firefox is started ...

### Expected Behavior

----

### Screenshots

----

### Additional Information

-----

**Comment by alexx7311** [comment] 2024-04-01 09:37
@Skywriter960 Hello! This problem is most likely related to a [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1885297#c4). The problem is very rare and we can't reproduce it, but if you can help us with it, it would be appreciated.

Please do the following:
1) Open the Browser console (press Ctrl + Shift + J (or Cmd + Shift + J on a Mac))
2) Choose Multiprocess mode and leave the Browser console opened
<details>
  <summary>Multiprocess mode</summary>

  ![Multiprocess mode](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/114913601/aa00993e-6eb2-4a8f-8e65-1bb1b1408ba2)

</details>

3) Follow steps 1-3 from this [instruction](https://maximtop.notion.site/How-to-export-logs-from-the-background-page-in-the-extension-fb7e2fe23cb0451ea010672ce0570929) for Firefox to open background page in the extension
4) Type each of these commands in the console of the background page:

`await browser.storage.local.get('adguard-settings');`

`await browser.storage.local.get('adguard-settings-2');`

`await browser.storage.local.set({'adguard-settings': 'test'});`

`await browser.storage.local.set({'adguard-settings-2': 'test'});`

`await browser.storage.local.remove('adguard-settings');`

`await browser.storage.local.remove('adguard-settings-2');`

5) Right click on any entry in console of the background page and click "Save All Messages to File" (as per step 4 in the [instruction above](https://maximtop.notion.site/How-to-export-logs-from-the-background-page-in-the-extension-fb7e2fe23cb0451ea010672ce0570929))
6) Go to the Events tab in Firefox at `about:telemetry#events-tab`
7) Type in "Find in Events" field "extensions.data" and take a screenshot, then "storageLocalError" and take a screenshot.

<details>
  <summary>Find in Events</summary>

  ![Find in Events](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/114913601/e488439d-4440-45db-bf8f-4f0156d763d9)

</details>

8) Navigate to the Browser console (from the step 1) and right click on any entry and click "Save All Messages to File".
9) Please attach all resulting files to the comment in this issue.

**Comment by alexx7311** [comment] 2024-04-04 08:39
@Skywriter960 Hello! Further discussion will be in https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775
If you would like to help us solve the problem, please leave a comment in that issue.

**Closed** 2024-04-04 08:40 UTC
Labels: Bug, Priority: P4
