### ISSUE TITLE
Improve AdGuard Extension Performance on LinkedIn

### ISSUE THREAD

**Issue by SujayNiranjan** [AdguardTeam/AdguardBrowserExtension#2991] opened 2024-10-07 13:21 UTC
### Issue Details

While the AdGuard Browser Extension works excellently for controlling ads on YouTube, it struggles with LinkedIn. The extension becomes slow and does not effectively manage ads on LinkedIn, leading to a less optimal user experience.

### Proposed solution

Optimize the AdGuard extension to enhance its performance on LinkedIn. This could involve fine-tuning the ad-blocking algorithms for LinkedIn-specific elements and improving resource management to ensure the extension runs smoothly without slowing down.

### Alternative solution

If direct optimization is challenging, consider offering users a tailored set of guidelines or custom filters specifically for LinkedIn, allowing users to manually adjust settings for better performance on the platform.

**Comment by windwak3r** [comment] 2024-10-14 10:48
@SujayNiranjan any updates?

**Comment by windwak3r** [comment] 2024-10-23 14:28
@SujayNiranjan We'll close the issue for now. Please leave a comment if the issue is still relevant.

**Closed** 2024-10-23 14:28 UTC
Labels: Feature Request, Waiting for data, Priority: P4

**Comment by SujayNiranjan** [comment] 2024-10-23 14:52
Hi @AlexandrPkhm, @windwak3r,

Apologies for the delayed response, and thanks for getting back to me! I'm using the latest version of the AdGuard extension from the Microsoft Edge store. The issue I'm facing is that when I enable the ad blocker, LinkedIn slows down significantly and becomes difficult to use. When I remove the adguard from the my extensions, then LinkedIn works faster.

Let me know if you need any more details to reproduce the issue.

Thanks for your help!

**Comment by windwak3r** [comment] 2024-12-09 15:36
@SujayNiranjan can you please export your AdGuard extension settings?

**Comment by SujayNiranjan** [comment] 2025-03-03 00:12
Apologies for the delay - {"protocol-version":"2.0","general-settings":{"allow-acceptable-ads":false,"show-blocked-ads-count":true,"autodetect-filters":true,"safebrowsing-enabled":true,"filters-update-period":-1,"appearance-theme":"system"},"extension-specific-settings":{"use-optimized-filters":false,"collect-hits-count":true,"show-context-menu":true,"show-info-about-adguard":false,"show-app-updated-info":true,"hide-rate-adguard":false,"user-rules-editor-wrap":false},"filters":{"enabled-filters":[2,3,4,224],"enabled-groups":[1,2,3,6,7],"custom-filters":[],"user-filter":{"enabled":true,"rules":"","disabled-rules":""},"allowlist":{"enabled":true,"inverted":false,"domains":["linkedin.com","t4wotc.com","receiveasmsonline.com","mail.google.com","ogsonline.ogs.nyu.edu","education.vex.com","app.outlier.ai","auth.openai.com","manage.autodesk.com","meet.google.com","office.com","cambrianrobotics.ai","groupon.com","chatgpt.com"],"inverted-domains":[]}},"stealth":{"stealth-disable-stealth-mode":true,"stealth-hide-referrer":true,"stealth-hide-search-queries":true,"stealth-send-do-not-track":true,"stealth-block-webrtc":false,"stealth-remove-x-client":false,"stealth-block-third-party-cookies":true,"stealth-block-third-party-cookies-time":2880,"stealth-block-first-party-cookies":false,"stealth-block-first-party-cookies-time":4320,"block-known-trackers":true,"strip-tracking-parameters":false}}
