### ISSUE TITLE
[Safari] Doesn't block useful ads on google.com, bing.com

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardBrowserExtension#57] opened 2015-11-13 13:11 UTC

**Comment by Mizzick** [comment] 2015-11-16 22:41
Cannot reproduce. Please check one more time and provide more details.

**Comment by ameshkov** [comment] 2015-11-16 22:55
Old version of Safari extension

**Comment by Mizzick** [comment] 2015-11-18 16:51
Fixed in #63 and #52

**Closed by Mizzick** 2015-11-18 16:51 UTC
Labels: Bug
