### ISSUE TITLE
Problem on Twitter (Adguard think it's another website)

### ISSUE THREAD

**Issue by SubActif** [AdguardTeam/AdguardBrowserExtension#1464] opened 2019-08-17 06:18 UTC
### Issue Details

- **AdGuard version:**
  - AdGuard v3.2.1
- **Browser and version:**
  - Firefox 68.0.2 (64 bits)
- **Operating system and version:**
  - Windows 10 (64) - 1903 (18362.295)
- **Filters you use in AdGuard:**
  - Adguard and Easylist Publicity
- **Stealth Mode settings:**
  - No
- **Other browser extensions:**
  - No

### Expected Behavior

To be very clear, all is in the screenshoot !
Many time when i go on Twitter, Adguard take the URL from a other opened page (and stay with this url after, F5 dont update the URL) !

After many try, i have found, Adguard keep the last URL after i start Twitter.
This is only with twitter.

Here i have open Google.com before, on the same onglet
![Sans titre](https://user-images.githubusercontent.com/17392472/63207554-7cb8f880-c0c8-11e9-9a52-714c2262e6ed.png)

### Screenshots
![Sans titre](https://user-images.githubusercontent.com/17392472/63207484-9a399280-c0c7-11e9-824d-86eb80d033c8.jpg)

**Comment by ameshkov** [comment] 2019-08-21 19:40
Duplicate of #1459

**Closed by ameshkov** 2019-08-21 19:40 UTC
