### ISSUE TITLE
Extension will be deleted by some browsers.

### ISSUE THREAD

**Issue by Muriashe** [AdguardTeam/AdguardBrowserExtension#2805] opened 2024-05-05 14:18 UTC
### AdGuard Extension version

4.3.46

### Browser version

FlashPeak Slimjet/Yandex Browser

### OS version

Windows 10 pro X86

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Good morning.

So, for a few months now, the extension has been deleted automatically.

I contacted Yandex Browser support, where I was told that it's an API error that's causing this.

It could be a conflict of extensions in the browser.

But I only use 2 extensions that are from Adguard.

Adguard and Adguard Extra.

The Yandex Browser shows a warning when you delete it.

“The authenticity of the extension has not been confirmed.

The “Adguard ad blocker” extension may have been installed without your knowledge.”

FlashPeak Slimjet only deletes the extension automatically.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
![ab7a0FRrOi](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/67009903/f42b10a2-ad9f-46dc-a698-002f00ebcb2c)

**Comment by alexx7311** [comment] 2024-05-06 09:35
@Muriashe 
Hello! Does the problem reproduce if you disable all other extensions except AdGuard?
What other extensions do you have installed and how often does AdGuard get deleted?

**Comment by Muriashe** [comment] 2024-05-08 14:45
@alexx7311 
Good morning.
So it always happens the same way.
I download and install the extension and everything is fine.
But after a few days the extension is automatically deleted.
In Yandex Browser the error I mentioned in the screenshot appears, while in the other browser the extension is just deleted.

**Comment by Muriashe** [comment] 2024-05-14 23:03
@alexx7311 

Good evening. 
So, I was testing the FlashPeak Slimjet (on the Edge the same thing happens) and now I've noticed this in the case of printing. The adguard is being deactivated, asking me to press to reload it.

![35Nis0W75E](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/67009903/924694d5-1933-4ae8-96be-f4b29b4ff867)

**Comment by alexx7311** [comment] 2024-06-10 11:38
@Muriashe Hello! Please do the following: 
1. Quit any running instance of Slimjet.
2. Right-click your Slimjet shortcut.
3. Select **Properties**.
4. At the end of the **Target**: line, add the command line flags: `--enable-logging --v=1`
5. With that example flag, it should look like: `slimjet.exe" --enable-logging --v=1`
6. Click `Apply` and then `OK`.
7. Launch Slimjet using your shortcut.
8. Reproduce the problem.

The file with debug logs will be stored in C:\Users\<YourUsername>\AppData\Local\Slimjet\User Data directory as chrome_debug.log

**Keep in mind that the log will be overwritten every time you open the browser.**

Please attach the file to the comment in this issue.

**Comment by Muriashe** [comment] 2024-06-10 18:23
@alexx7311 
Good afternoon.

Sorry for the delay in replying.

Note: The record has been renamed to 1.1 so as not to create a new record.

[chrome_debug 1.1.log](https://github.com/user-attachments/files/15777599/chrome_debug.1.1.log)

**Comment by alexx7311** [comment] 2024-06-11 08:52
@Muriashe There are no extension related errors in these logs. Please collect the logs containing the extension crash.

**Comment by alexx7311** [comment] 2024-06-21 08:43
@Muriashe Hello! Any updates?

**Comment by alexx7311** [comment] 2024-07-01 08:59
@Muriashe We'll close the issue for now as we cannot reproduce it. Please leave a comment if the problem is still relevant.

**Closed** 2024-07-01 08:59 UTC
Labels: Bug, Priority: P4
