### ISSUE TITLE
AdGuard does not block all resources with User rules

### ISSUE THREAD

**Issue by 666f78** [AdguardTeam/AdguardBrowserExtension#2808] opened 2024-05-09 19:11 UTC
### AdGuard Extension version

Version 4.3.46

### Browser version

Version 124.0.6367.156 (Official Build) (64-bit)

### OS version

win11

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters

### Issue Details

AdGuard does not block all resources with User rules
To reproduce, open the [site ](https://uaserials.pro/1015-hannibal.html)and play the video

### Expected Behavior

Resource should be blocked

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/20286171/5e20b52b-0c1a-421b-a520-60d97c524367)
</details>

<details><summary>Screenshot 2:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/20286171/4baed213-3735-427a-8d24-33e329086639)
</details>

**Comment by alexx7311** [comment] 2024-05-13 09:46
@666f78 Hello! We couldn't reproduce the problem. Please try clearing your browser cookies or use your browser's incognito mode. If you use other ad blockers, please disable them.

**Comment by alexx7311** [comment] 2024-05-15 13:30
@666f78 We were able to reproduce this problem and another similar problem.
Closing as dup. of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2811, you can follow the problem there.

**Closed** 2024-05-15 13:31 UTC
Labels: Bug, Priority: P4
