### ISSUE TITLE
Inverted Whitelist does not work when using search engines from SpeedDial page in Opera

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardBrowserExtension#1049] opened 2018-07-18 14:42 UTC
AdGuard misbehaves when using search engines from the speed dial page in Opera.

### Steps to reproduce

1. Go to Extension > Whitelist
2. Enable the Inverted whitelist, add a website there
3. Go to that website, see AdGuard working which is expected
4. Go to the Speed Dial page, type a search request in Google or Yandex 

### Expected behavior

AdGuard does not filter the page

### Actual behavior

It actually does work there, disabling filtering manually does not have any effect

<details><summary>Screen recordingt:</summary>

https://uploads.adguard.com/screencast_07-18-17-44.mp4

</details>

### Your environment

* AdGuard AdBlocker extension version: 2.9.2 for Opera
* Environment name and version: Opera 54.x
* Any other browser extensions you have installed: none

**Comment by ameshkov** [comment] 2018-09-04 19:10
Most likely this is a bug of Opera. We'll figure what exactly is wrong and file a bug report to them.

**Comment by JonnyRedHed** [comment] 2018-09-10 16:27
Any progress bug with isolating the bug.

**Comment by ameshkov** [comment] 2018-09-12 22:38
@JonnyRedHed not yet. The issue is assigned to v3.0 while we're a bit busy preparing a hotfix for v2.10 with a couple major bugfixes.

**Comment by JonnyRedHed** [comment] 2018-09-15 18:35
I'm sure like many Opera users who search via the new tab google search box, that we use it many times a day.   I hope a fix comes soon.

**Comment by Mizzick** [comment] 2018-11-20 13:54
Reproduced with Opera 56

**Comment by JonnyRedHed** [comment] 2018-11-20 18:46
Same for me. About time this was fixed, adguard not working with google search from new tab or url bar search.

**Comment by Mizzick** [comment] 2018-11-21 18:16
Found the reason, there is no DOCUMENT type request presented in `browser.webRequest.onBeforeRequest` listener in case of typing in google search from new tab or url bar search.

**Comment by Mizzick** [comment] 2018-11-21 18:30
Submitted a bug to Opera tracker.

**Comment by ameshkov** [comment] 2018-11-21 19:33
> Found the reason, there is no DOCUMENT type request presented in browser.webRequest.onBeforeRequest listener in case of typing in google search from new tab or url bar search.

Opera is not alone here btw. As I recall, Yandex Browser suffers from the very same issue.

> Submitted a bug to Opera tracker.

Is there any bug ID so that we could track how it goes?

**Comment by Mizzick** [comment] 2018-11-25 14:51
Bug id: `DNAWIZ-46137`

**Comment by JonnyRedHed** [comment] 2018-12-10 13:56
How do we track this bug id with Opera.  Any progress yet.

**Comment by ameshkov** [comment] 2018-12-10 14:53
@JonnyRedHed there's no easy way to track it -- their bug tracker is not open

**Comment by JonnyRedHed** [comment] 2018-12-10 17:21
Ah I see, I did not know that.

**Comment by JonnyRedHed** [comment] 2019-03-29 07:45
Has any progress been made with this.

**Comment by JonnyRedHed** [comment] 2019-08-02 17:15
Bug still not fixed by Opera.  Can' Adguard devs speak to them directly about fixing this issue please.

**Comment by ameshkov** [comment] 2019-08-04 15:47
We did report it to them, but there's no one we can speak to directly:(

**Comment by JonnyRedHed** [comment] 2019-09-26 08:39
Ok thanks. I guess thats all can done at present.

**Comment by ameshkov** [comment] 2019-10-03 22:15
Actually, there is a chance that the workaround we're using for #1459 might help with this issue as well.

@maximtop could you please take a look? Am I right that fixing #1459 can help?

**Comment by maximtop** [comment] 2019-10-04 08:13
> @maximtop could you please take a look? Am I right that fixing #1459 can help?
yeah seems to be working as expected, I'll move this issue to QA&Review board.

**Closed** 2019-10-23 10:36 UTC
Labels: Browser Bug: Opera
