### ISSUE TITLE
Cannot Subscribe to Custom Local Filter

### ISSUE THREAD

**Issue by RianGray** [AdguardTeam/AdguardBrowserExtension#1700] opened 2020-09-09 15:56 UTC
### Issue Details

- **AdGuard version:**
  - AdGuard extension for Firefox 3.5.12 and AdGuard extension for Chrome 3.5.12
- **Browser and version:**
  - Firefox 80.0.1 and Chrome 85.0.4183.102
- **Operating system and version:**
  - macOS Catalina 10.15.6
- **Filters you use in AdGuard:**
  - Adguard Base filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter, NoCoin Filter List, YousList, foo.filter(test purposes)
- **Stealth Mode settings:**
  - Not using
- **Other browser extensions:**
  - 1Password, ExpressVPN, HTTPS Everywhere, Image Picka, Tab Session Manager

### Expected Behavior

When I provide the path for a filter on the computer, (i.e. '~/foo.txt' or '/Users/username/foo.txt') AdGuard would subscribe to the filter much like subscribing to any other filters.

### Actual Behavior

Upon entering the path to the filter file, AdGuard produces following error message: "Error while adding your custom filter".

### Screenshots

<details><summary>Screenshot: Error message pop-up from Firefox, same message produced on Chrome</summary>

<img width="1697" alt="Screen Shot 2020-09-10 at 12 40 55 AM" src="https://user-images.githubusercontent.com/22567097/92621643-043e5e80-f2ff-11ea-9a24-ab5bd7ee6db1.png">

</details>

### Additional Information

 I've encountered a problem after trying to have all my browsers use custom filter feature, rather then copy/pasting it to user filter every time. While I didn't have any issues subscribing a filter on Safari, Firefox produced an error message on Mac. To confirm the issue was not related to my personal filter, I've made a test file named foo.txt with some generic titles filled in, but it still produced an error message. I've also tested on Chrome (which I rarely use), I got a same error message.

**Comment by Chinaski1** [comment] 2020-09-10 14:02
Duplicate of #1697

**Closed by Chinaski1** 2020-09-10 14:02 UTC
Labels: Duplicate
