### ISSUE TITLE
Speed issue on Safari

### ISSUE THREAD

**Issue by tiberian83** [AdguardTeam/AdguardBrowserExtension#251] opened 2016-05-21 06:59 UTC
Adblock on Safari with the old API is much slower than for example uBlock with the same filters. Even the new API is still slower than uBlock. Hopefully this can be fixed in a future release to match the same speed in loading pages as uBlock. On Chrome there seems to be no speed issue though.

**Comment by tiberian83** [comment] 2016-05-21 12:34
Some examples are:

www.tdg.ch
www.blick.ch
www.20min.ch

**Comment by ameshkov** [comment] 2016-05-23 15:14
@tiberian83 have you tried the latest beta release?

**Comment by ameshkov** [comment] 2016-05-23 15:14
> Even the new API is still slower than uBlock

Huh, that just can't be resolved by us:)

**Comment by tiberian83** [comment] 2016-05-24 09:00
Yes, I tried the 2.3.4 beta. It's just weird that uBlock is lightning fast and Adguard needs much longer on several pages.

**Comment by ameshkov** [comment] 2016-05-24 09:23
I see an issue on blick.ch with an old API. It renders hundreds of images dynamically, for each image we call "canLoad" synchronously which slows the whole page rendering down. I guess 

It is not yet clear to me what should we do. On one hand, the old API is deprecated and should be removed from Safari in future versions. On the other hand, I don't know when this future come:)

@Mizzick what is really bad is that I see that in the current beta AG still uses the old API along with the old! It seems that "contentBlockerEnabled" check works not as it should.

**Comment by tiberian83** [comment] 2016-05-24 09:30
Maybe this is it. I remember that uBlock also was very fast on forums.plex.tv although it had the same issue than Adguard (blocking one Image several times).

Maybe the same issue also happens on www.tdg.ch and www.tagi.ch ?

The new API is faster than the old API, even though uBlock is still faster. But I think uBlock uses some trick to get that fast because sometimes not all rules are used correctly and I have to reload the page for showing everything right (www.gamestar.de is such an example).

**Comment by ameshkov** [comment] 2016-05-24 09:30
@Mizzick created a new task for the contentBlockerEnabled flag issue:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/254

**Comment by ameshkov** [comment] 2016-05-24 09:31
@tiberian83 the new API is faster than the old API, even though uBlock is still faster

I guess that's because of #254, it seems that AG now uses **both** API

**Comment by ameshkov** [comment] 2016-05-24 09:32
@tiberian83 
> But I think uBlock uses some trick to get that fast because sometimes

Yep, that's for sure. And I am not sure that we should use the same trick. I am not against performance though, I just don't think Apple will keep the old API alive long enough.

**Comment by tiberian83** [comment] 2016-05-24 09:38
> I guess that's because of #254, it seems that AG now uses both API
I'm looking forward to the new beta.

> I am not against performance though, I just don't think Apple will keep the old API alive long enough.
I totally understand you. The reason why I still prefer the old API though is the 50'000 rules limit in the new API.

**Comment by ameshkov** [comment] 2016-05-24 09:48
Yep, pretty weird limitation, they need it on mobile devices though, as content blocker compilation takes much time there.

**Comment by ameshkov** [comment] 2016-05-30 21:43
@tiberian83 thank you for creating this issue, after all it appeared to be an important problem.

So, this issue was caused by the fact that we synchronously updated "blocked" items counter in the extension local storage. It appears to be a slow operation in case of Safari. What's bad is that in case of Safari everything is done on the UI thread, so this operation slowed down rendering process as well.

**Closed by ameshkov** 2016-05-30 21:43 UTC
Labels: Safari

**Comment by tiberian83** [comment] 2016-05-31 06:40
You are welcome. I'm glad I could help. :-) I'm looking forward to the next release.
