### ISSUE TITLE
Unable to add custom rules to AdGuard in Edge

### ISSUE THREAD

**Issue by superbigsteam** [AdguardTeam/AdguardBrowserExtension#2674] opened 2024-01-04 15:14 UTC
### AdGuard Extension version

AdGuard 浏览器扩展 版本 4.2.241

### Browser version

edgebata

### OS version

Windows 11 专业版22631.2861

### Issue Details

adguard 的edge把他扩展无法添加自定义规则
这是规则列表
[https://[raw.githubusercontent.com/guandasheng/TheBestAdrules/master/rules.txt]](https://raw.githubusercontent.com/guandasheng/TheBestAdrules/master/rules.txt)https://[raw.githubusercontent.com/guandasheng/TheBestAdrules/master/rules.txt](https://raw.githubusercontent.com/guandasheng/TheBestAdrules/master/rules.txt)

**Comment by alexx7311** [comment] 2024-01-09 10:10
@superbigsteam We couldn't reproduce the problem. The rules at the link you provided are not available. Please make sure the link is correct.

Please check if the problem reproduces with other links to the rules, e.g. https://easylist.to/easylist/easylist.txt

**Comment by alexx7311** [comment] 2024-01-22 08:49
@superbigsteam The issue will be closed in a few days if we won't get a response.

**Comment by alexx7311** [comment] 2024-01-29 09:03
@superbigsteam If you'd like us to look into the issue further, please leave a comment.

**Closed** 2024-01-29 09:03 UTC
Labels: Bug, Priority: P4
