### ISSUE TITLE
Custom filter is not saved when exporting settings

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1224] opened 2018-12-28 15:02 UTC
### Steps to reproduce

1. Import custom filter(URL)
2. Export settings

### Actual behavior
URL of custom filter is absent in `export.json`
`"custom-filters":[]`

### Your environment

* AdGuard AdBlocker extension version: 3.01
* Environment name and version: Chrome

**Comment by karina-archazh** [comment] 2019-02-05 15:05
In MS Edge import settings doesn't work

**Comment by maximtop** [comment] 2019-02-06 13:03
Export in the edge is not working due to this bug https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8178877/
but you still can check if the issue is resolved in the edge if you copy a string from the exported HTML file to some JSON file.

**Closed** 2019-02-07 12:45 UTC
Labels: Bug, P3: Medium
