### ISSUE TITLE
$removeparam modifier should not remove search params from POST requests

### ISSUE THREAD

**Issue by BrokenShoeLace** [AdguardTeam/AdguardBrowserExtension#1812] opened 2021-05-26 01:37 UTC
The above extension automatically installed and has a few bugs

The $removeparam breaks bing.com so it does nothing

If in Android, I click the ... in Firefox, Add-ons then choose Adguard. Now select block ads on this site and a toolbar appears. Choose the advert container and click the tick for absolutely nothing to happen

That annoying box outline just keeps jumping all over the page for no reason. Disable Adguard or uninstall it for the box to disappear.

How do I get the previous version back?

**Comment by maximtop** [comment] 2021-05-26 04:08
Hi,
Could you, please clarify few questions
Do you use the extension on Firefox for Android?
Did you add some rule with the $removeparam modifier or just enabled the AdGuard URL Tracking filter?

I have installed the extension in macOS, and Firefox for Android, enabled the AdGuard URL Tracking filter and bing.com seems to be working as expected.

To remove outlining box you should press cross on the bar at the bottom of the screen https://uploads.adguard.com/Screenshot_20210526-065906_Firefox.png, or refresh the page.

Could you provide steps to reproduce, please?

**Comment by BrokenShoeLace** [comment] 2021-05-26 06:38
Hi,

Yes, it is the Android Extension for Firefox (Fenix)

Yes, I did add a rule for Bing using the guide about parameters and the documentation said it wouldnt remove it as it only removes on a GET but the url after bing.com was added to on POST. With the new version of the extension, it finally removed everything after the bing.com like the rule was for but then bing search engine just postbacked and lost all search criteria returning a blank page. I removed my rule which was just 

bing.com^$removeparam where all the utm stuff was listed plus a toWww-1

https://www.bing.com/?toWww=1&redig=F3EA159E06F465A4D705316EB7B18E18

Also, previous version wouldnt catch your filter guide url where it substitues a word for utm...

The toolbar with the tick, preview, +, - and X. If you follow my instructions in the original post you could surround the advert, press preview to check its what you wish to hide, unclick preview and press the tick (on previous version the toolbar would go and you needed to repeat to remoce the next item.) it is supposed to add the rule and close the toolbar but now it doesnt do anything and doesnt add the rule. On the extension for Firefox for Windows 10 Desktop, its on 3.6.5 but everything works ok; saving and adding rule and no flickering black bordered transparent box jumping all over the mobile browser window.

In Visual Studio, there used to be a tool that would find a window in the desktop and surround  it with a border. To me, this jumping box that occurs when Adguard is installed reminds me of that amazing tool. Your screenshot is not the jumpy box. 

If you look at the following urls you will see a line of text with a line through it. That is obviously one edge of a jumpy box. However, the 3rd image shows the top and bottom outlines of that box.

https://ibb.co/pzkQ48z
https://ibb.co/nDXdPkP
https://ibb.co/64GVxPQ

I usually would use imgurl.com but now Adguard has stopped that site from working

Hope you get this sorted soon.

**Comment by maximtop** [comment] 2021-05-26 08:27
I'll fix removing parameters from POST requests as soon as possible, thank you for reporting it.

But as far as I see it won't let bing.com work with the rule `bing.com^$removeparam`. Almost all requests sent on bing.com after clicking search have the method GET. See screenshot https://uploads.adguard.com/Image_2021-05-26_10-51-16.png.

Regarding the assistant, I was not able to reproduce your issue. I've asked a member of the QA team to check, but he was unable to reproduce too. Maybe you can record a video?
Anyway, I'd like to note that in this release we didn't update the version of AdGuard Assistant, that's why there is not a big chance that its behavior changed.

**Comment by krystian3w** [comment] 2021-08-29 21:12
test

**Comment by Birbber** [comment] 2021-09-22 13:51
@BrokenShoeLace Hi!
Is this issue still reproducible or I can close this one?

**Comment by Mohammadsaead69** [comment] 2021-09-23 06:01
Hey,Anna
Yeah...please close this one

**Comment by Mohammadsaead69** [comment] 2021-09-23 06:02
And I need help becuse I’m not understanding what is the right

**Comment by BrokenShoeLace** [comment] 2021-09-23 07:08
Resoved - thank you team!

**Closed** 2021-09-23 07:08 UTC
Labels: Resolution: Fixed, Status: Resolved, Version: AdGuard v3.6

**Comment by Birbber** [comment] 2021-09-23 10:08
@Mohammadsaead69 What do you mean?
