### ISSUE TITLE
Blocked iframe "flickering" all the time

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#301] opened 2016-07-25 12:34 UTC
Source:
https://forum.adguard.com/index.php?threads/is-it-possible-to-cache-post-processing-results.12120/

Currently AG applies post-processing rules to images and frames. We wait either for "load" or "error" events and then check if these elements should be blocked:
```
        document.addEventListener("error", checkShouldCollapse, true);

        // We need to listen for load events to hide blocked iframes (they don't raise error event)
        document.addEventListener("load", checkShouldCollapse, true);
```

This indeed causes some sort of flickering on page load. Implementing a post-processing cache would definitely improve user experience.

There are two questions though:
1. How to flush the cache? I suggest we add a "requestFilter.version" field, which will be passed to the content script in the "getSelectorsAndScripts" callback. Depending on this version we should either use cached selectors or flush the cache.
2. How to cache? What will be the element ID? URL? Full CSS path or xpath?

**Comment by ameshkov** [comment] 2016-07-25 12:34
@Mizzick what do you think about it?

**Comment by Mizzick** [comment] 2016-07-25 14:41
But how can it fix the flickering problem?
As I see, it's about the moment we apply our selectors, for sure a cache can help us to make it a bit faster but will not solve the issue.

**Comment by ameshkov** [comment] 2016-07-25 15:15
The root cause of this flickering is that we allow element to load. With a cache we could hide known elements right away and then (after the check is finished) either unhide it or leave hidden.

**Comment by SlowMemory** [comment] 2016-07-25 15:36
I posted the thread in the forum and I am sorry for wasting your time on this, I don't even know what "cache" precisely means, so this may not make sense.

When an iframe is blocked after a page is loaded, it shows an image like this http://imgur.com/a/Qvuuq for a short time, and this is what I refered as a flickering. If the hidden iframe is <iframe src="X">, I am wondering if Adguard can "cache" a rule ##iframe[src="X"] or a "stylesheet" iframe[src="X"] { display:none!important;} to this page, so that this rule is applied after refreshing the page and images like above is hidden.

**Comment by ameshkov** [comment] 2016-07-25 15:46
Hm, the issue is specific for iframes and I think I know why.
@Mizzick forget about the cache, look at the "checkShouldCollapse" method.
```
...
        if (eventType == "error") {
            // Hide elements with "error" type right now
            // We will roll it back if element should not be collapsed
            collapseElement(element, tagName);
        }
...
```

The thing is that for iframes eventType is always "load", it just cannot be "error". So, we could do something like that instead:
```
...
        if ((eventType == "error") || (tagName == "iframe")) {
            // Hide elements which are likely to be blocked right now.
            // Please not, that "iframe" cannot raise "error" event so we always hide it.
            // We will roll it back if element should not be collapsed
            collapseElement(element, tagName);
        }
...
```

**Comment by Mizzick** [comment] 2016-07-25 16:23
Seems like it doesn't help.

**Comment by Mizzick** [comment] 2016-07-25 20:07
Fixed

**Comment by SlowMemory** [comment] 2016-07-26 04:40
It seems that now iframes with src attribute starting with http are somehow hidden, but aren't there iframes like `<iframe src="/advertisement/...">`, `<iframe src="//www/delivery..">`, or  `<iframe src="../advertisement/banner.html">`? will these be hidden as well?

**Comment by Mizzick** [comment] 2016-07-26 12:22
You are right.

**Comment by ameshkov** [comment] 2016-07-26 12:46
@Mizzick maybe at least `iframe[src]`?

**Comment by Mizzick** [comment] 2016-07-26 13:42
@ameshkov do you think it's a big difference?

**Comment by ameshkov** [comment] 2016-07-26 13:46
Iframes are sometimes used for messaging and such, so i guess it could be useful to hide only those with "src" attribute.

**Comment by Mizzick** [comment] 2016-07-26 13:48
okay

**Comment by SlowMemory** [comment] 2016-07-29 14:17
I am wondering, does this function expected to work even if I am using the extension as an integration mode? I sometimes see iframe[src] { display:none!important; } in the inspector.

**Comment by ameshkov** [comment] 2016-07-29 21:43
@Mizzick we have forgot about it! Style should be removed as well if we receive an empty response form the background page.

**Comment by Mizzick** [comment] 2016-08-01 10:25
```// Removing added iframes-hiding style
        // We do it here, cause otherwise it's not working properly
        removeIframeHidingStyle();

        if (!response) {
            return;
        }```

it will be removed

**Comment by Mizzick** [comment] 2016-08-01 11:04
ok, fixed

**Comment by SlowMemory** [comment] 2016-08-01 13:39
I am still seeing adguard-frames-style when I am using the extension as an integration mode.
Screenshot: http://i.imgur.com/PDv0f0l.png

**Comment by ameshkov** [comment] 2016-08-01 16:46
@SlowMemory cannot reproduce, are you sure you've used the latest version from the "master" branch?

**Comment by ameshkov** [comment] 2016-08-01 19:06
@Mizzick it is back in the beta:(

**Comment by Mizzick** [comment] 2016-08-03 09:45
Fixed with an other way, @SlowMemory please take a look?

**Comment by SlowMemory** [comment] 2016-08-03 11:55
I was using an old version, the problem is gone in the latest version but maybe the other fix is not needed.

**Comment by Alex-302** [comment] 2016-08-04 20:03
When extension works in integration mode, the player on fs.to is hidden by iframe[src]

**Comment by ameshkov** [comment] 2016-08-04 21:24
@Mizzick maybe we should call `addIframeHidingStyle` inside `processCssAndScriptsResponse` when we are sure AG should work for this page?

Also what if `DOMContentLoaded` won't be called? We'd better check `document.readyState` as well.

**Comment by Mizzick** [comment] 2016-08-05 11:15
Good idea!

**Comment by ameshkov** [comment] 2016-08-05 11:16
Don't forget about readyState! DOMContentLoaded could already fired at the time of CSS message arrival.

**Comment by Mizzick** [comment] 2016-08-05 12:14
Okay!

**Comment by SlowMemory** [comment] 2016-09-01 12:56
I'd like to report that 2.4.10 does not resolve this issue. I was downloading extensions from this page: https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v2.4.10
I've tested with Firefox (50.0a2) and Chrome (52.0.2743.116 m). Some blocked iframes are still flickering, and some are not collapsed. This was observed on my end in news.naver.com and tvple.com with English filter, List-KR enabled.

**Comment by ameshkov** [comment] 2016-09-06 16:34
Ah, what a stupid mistake.

@Mizzick response.selectors does not have length attribute anymore

```
        if (response && response.selectors && response.selectors.length > 0) {
            addIframeHidingStyle();
        }
```

**Comment by Mizzick** [comment] 2016-09-06 17:02
Fixed

**Closed by Mizzick** 2016-09-06 17:02 UTC
Labels: Bug, Question
