### ISSUE TITLE
The applied rule is not displayed in the filtering log

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardBrowserExtension#1388] opened 2019-04-29 12:20 UTC
The rule is not displayed:

rp5.by,rp5.kz,rp5.ru,rp5.ua#$##content > div > div[id]:has(> ins.adsbygoogle) { position: absolute!important; left: -3000px!important; }

### Steps to reproduce

1. Open [link](https://rp5.ru/%D0%9F%D0%BE%D0%B3%D0%BE%D0%B4%D0%B0_%D0%B2_%D0%90%D0%BB%D0%B5%D0%B9%D1%81%D0%BA%D0%B5)
2. Open filtering log

See the screenshots attached below.

<details><summary>Screenshot:</summary>

![im](https://uploads.adguard.com/TheHasagilcyx1.jpg)

![img](https://uploads.adguard.com/TheHasagi1fb1w.jpg)

</details>

**Comment by maximtop** [comment] 2019-04-29 12:34
duplicate of #1370

**Closed by maximtop** 2019-04-29 12:34 UTC
Labels: Bug, P3: Medium
