### ISSUE TITLE
"Indicate the number of blocked ads on the Adguard extension icon" - not available in 2.1.2?

### ISSUE THREAD

**Issue by Fofer** [AdguardTeam/AdguardBrowserExtension#141] opened 2016-01-23 20:44 UTC
I have been running AdGuard AdBlock 2.0.16 in OS X Safari 9.0.3 for a bit and love it.  Thanks so much for making it. I just upgraded to the beta of 2.1.2 though, to check out the new content blocking mechanism.  The first thing I noticed was that there is no longer an option to "Indicate the number of blocked ads on the Adguard extension icon."  As such it's difficult to tell when content has in fact, been blocked, and I also didn't see any "magnifying glass" icon in the pull-out menu, that lets me inspect each blocked element, to whitelist if I need to.  The removal of this makes troubleshooting issues really difficult. 

Has this feature been removed from the soon-to-be-released new version?  I hope it can be included, even just as an option? Because without that functionality I'm afraid I'd have to switch again to yet another ad blocker extension.

**Comment by Fofer** [comment] 2016-01-23 20:53
I now see this has been addresses elsewhere by the developer:

"Yep, that's a problem we can't solve by ourselves.  You see, Safari does not provide any feedback mechanism so extension does not know what is blocked. That's why our "filtering log" is disabled in Safari version.

I've requested this feature back in Novemeber in webkit-help, but it seems nobody reads that mailing list.
https://lists.webkit.org/pipermail/webkit-help/2015-November/003994.html

So I have just filed a feature request in the bugzilla:
https://bugs.webkit.org/show_bug.cgi?id=152598

Please vote for this request there if you want it to be implemented."

http://forums.macrumors.com/threads/the-el-capitan-safari-9-content-blocker-thread.1924936/page-7#post-22413144

**Comment by ameshkov** [comment] 2016-01-24 21:24
It seems that this issue is duplicate for #143

Let's wait for @Mizzick to check if it's possible to switch to old API in real time.
At least we could create a separate build using the old API.

**Comment by ameshkov** [comment] 2016-01-27 15:05
Closed as duplicate of #143.

**Closed by ameshkov** 2016-01-27 15:05 UTC
Labels: Safari
