### ISSUE TITLE
Conflict b/w Annoyance Filter & Send Statistics

### ISSUE THREAD

**Issue by The-Commissioner** [AdguardTeam/AdguardBrowserExtension#405] opened 2016-10-14 15:32 UTC
First of all @vozersky @Bohdan-SUP I would like to draw your attention to Ticket #YQZ-381-15978
The title clearly states it being a Extension problem yet support posted it in the Filters issue. 
See here: https://github.com/AdguardTeam/AdguardFilters/issues/3190
Add to that, he/she missed posting a vital piece of info. Just reviewing.

**Issue**
Using adguard beta extension on FF 2.4.14 on FF stable 49.0.1 x64

Custom/User element hiding filter rules do not work on https(encrypted sites) if 'Send statistics for ad filters usage' is enabled in Miscellaneous category.

I have English, Spyware, Social,Annoyance, Easyprivacy and FB annoyances as my primary filter lists.....

According to me, the problem is compatibility/conflict b/w Annoyance filter and Send Statistics option.

Here is an example of my rules for forum.adguard.com:-
`forum.adguard.com###english-forums\.47 > .nodeList > .node_84.level_2.category_forum.node
forum.adguard.com###english-forums\.47 > .nodeList > .node_79.level_2.category_forum.node
forum.adguard.com###english-forums\.47 > .nodeList > .node_74.level_2.category_forum.node
forum.adguard.com###russian-forums-russkie-forumy\.3`

these rules are supposed to hide the russian part of the forum, the the mac subforum, the adguard IOS subforum and the android subforum. this doesn't work in the scenario discussed in the above posts and I see the full site.

**Comment by ameshkov** [comment] 2016-10-17 12:45
Hm, it very well could be the filters issue.

@Mizzick could you please extract the global stylesheet contents and post it here?

**Comment by The-Commissioner** [comment] 2016-10-20 09:46
I'm pissed off by the support service to the extreme, I no longer want to support, test or use this app/extension in any form. Closing the issue.

**Comment by vozersky** [comment] 2016-10-20 10:22
can't reproduce it on both vm and actual windows machine 
@gshumihin could you give it a try?

**Comment by ameshkov** [comment] 2016-10-20 11:17
@The-Commissioner 
There is no need in closing this issue, this is still a possible bug with how styles are applied when "send stats" option is checked.

**Comment by vozersky** [comment] 2016-10-20 12:33
confirmed with 2.4.14 beta

**Comment by ameshkov** [comment] 2017-03-22 16:21
The bug was resolved in FF v2.5

**Closed by ameshkov** 2017-03-22 16:21 UTC
Labels: Firefox
