### ISSUE TITLE
Chrome Browser Freezing When Accessing ACS Websites with AdGuard Extension

### ISSUE THREAD

**Issue by zfchem** [AdguardTeam/AdguardBrowserExtension#2885] opened 2024-07-25 17:57 UTC
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard Extension version

4.3.53

### Browser version

Chrome 127.0.6533.73

### OS version

Windows 11

### Issue Details

Steps to reproduce:
1. Open Google Chrome.
2. Navigate to the ACS Website.
3. Access Any Literature Page.
4. Observe Browser Behavior.

Example link: https://pubs.acs.org/doi/10.1021/jacs.4c03117

### Expected Behavior

When navigating to any literature page on the ACS website using Google Chrome with the AdGuard Browser Extension enabled, the page should load normally.

### Actual Behavior

When navigating to any literature page on the ACS website using Google Chrome with the AdGuard Browser Extension enabled, the browser freezes.
CPU and RAM usage spike to 100%, significantly impacting the performance of the entire system.
The issue persists until the Chrome browser is forcibly closed and reopened.
Disabling the AdGuard Browser Extension resolves the issue, indicating the problem is likely caused by the extension.

### Screenshots

<details><summary>Screenshot 1</summary>

<
![Screenshot 2024-07-23 163030](https://github.com/user-attachments/assets/3b385332-bd04-4fd1-9a57-7f1cd11ab760)
>

</details>

**Comment by alexx7311** [comment] 2024-07-26 16:16
@zfchem Hello! Does the problem reproduce on the latest beta https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.4.7-beta ?

**Comment by zfchem** [comment] 2024-07-26 17:13
> @zfchem Hello! Does the problem reproduce on the latest beta https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.4.7-beta ?

The latest beta solves the problem! Thank you!

**Comment by alexx7311** [comment] 2024-08-23 16:46
@zfchem 4.4 stable version is out too! https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.4.18
We'll close the issue for now. Please leave a comment if the problem is still relevant.

**Closed** 2024-08-23 16:46 UTC
Labels: Bug, Priority: P4
