### ISSUE TITLE
edition.cnn.com - some element hiding rules are not applied in Firefox

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#2206] opened 2022-10-10 09:15 UTC
@adguard-bot commented on [Fri Oct 07 2022](https://github.com/AdguardTeam/AdguardFilters/issues/131610)

### Issue URL (Annoyance)
 [https://edition.cnn.com/2022/10/06/entertainment/hellraiser-review/index.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fedition.cnn.com%2F2022%2F10%2F06%2Fentertainment%2Fhellraiser-review%2Findex.html)
### Comment
Username: @scrutinizer11
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/DRKjWGV.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v4.1.37
Browser: | Firefox
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Strip URLs from tracking parameters, <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection, <br/>EasyPrivacy, <br/>Fanboy's Enhanced Tracking List<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist, <br/>NoCoin Filter List<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Other extensions used: | Wayback Machine, iCloud dashboard, Click to Shorten URL, Dark Reader, Grammarly, Enhancer for YouTube, Share with SNS, Stylus, File Converter by Convert-Online.com, Mate Translate

---

@Alex-302 commented on [Fri Oct 07 2022](https://github.com/AdguardTeam/AdguardFilters/issues/131610#issuecomment-1271568996)

@scrutinizer11 Hi. Not reproduced, an applied rule is on screenshot below. 
What do you see in the filtering log? Please make a screenshot.

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/194560672-b9c00a32-d041-4027-857f-1990fdcb2508.png)

</details>

---

@scrutinizer11 commented on [Fri Oct 07 2022](https://github.com/AdguardTeam/AdguardFilters/issues/131610#issuecomment-1271575974)

Modified rules screenshots:

![Screen Shot 2022-10-07 at 16 09 52](https://user-images.githubusercontent.com/45983734/194561804-492f4273-7afc-4e70-94a3-f54da21f3091.png)
![Screen Shot 2022-10-07 at 16 10 16](https://user-images.githubusercontent.com/45983734/194561815-7d416f67-16d3-4aa6-a537-e8ce90a5206d.png)

---

@BlazDT commented on [Sat Oct 08 2022](https://github.com/AdguardTeam/AdguardFilters/issues/131610#issuecomment-1272236317)

Please try to enable Annoyances/cookies filter 

---

@scrutinizer11 commented on [Sun Oct 09 2022](https://github.com/AdguardTeam/AdguardFilters/issues/131610#issuecomment-1272265032)

The issue is systemic and has been reported already. Updating to 4.1.36 from 4.1.22 has wiped out all filters and rule settings. Now, every time I start a new Firefox session Adguard opens its page (not the AG website, but the AG extension's page) in a separate tab as highlighted in [https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2189#issue-1374648005](url). Once Firefox has been quit AdGuard resets all its settings to start anew the next time. The extension is broken.

That's what I see every time I launch Firefox. Ironically, there's AG's cookie warning escaping Adguard rules because they're disabled. That never used to be the case.

![Screen Shot 2022-10-08 at 11 30 08](https://user-images.githubusercontent.com/45983734/194698258-0e441baf-9108-4b95-aef4-6c911e96b823.png)

---

@Alex-302 commented on [Mon Oct 10 2022](https://github.com/AdguardTeam/AdguardFilters/issues/131610#issuecomment-1273018254)

> Updating to 4.1.36 from 4.1.22 has wiped out all filters and rule settings

In my Firefoxes all good. Maybe this is browser build or browser profile issue.
I see your problem here https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2189

In any case, this problem(bug) is not related to this issue. Will move to AdguardBrowserExtension

**Comment by Alex-302** [comment] 2022-10-10 09:16
@scrutinizer11

**Comment by Birbber** [comment] 2022-10-13 13:00
Closing this issue as a duplicate of #2189. As for the initial request enabling Annoyances/cookies filter should help.
Please re-open in case of additional questions.

**Closed by Birbber** 2022-10-13 13:00 UTC
