### ISSUE TITLE
Firefox extension No Rules apply when turn on the pc

### ISSUE THREAD

**Issue by mad-hin** [AdguardTeam/AdguardBrowserExtension#2441] opened 2023-08-20 09:46 UTC
### AdGuard Extension version

4.1.57

### Browser version

Firefox 116.0.2

### OS version

Manjaro, Windows 11, MacOS

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard Tracking Protection filter

### What Stealth Mode options do you have enabled?

Block trackers

### Issue Details

The Firefox extension will not apply any rules form the filters unless I update the filter manually every time I turn on my pc  

### Expected Behavior

It is expected to have some rules to being applied when I turn on the pc and start up the browser. It should also update the filters by itself

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maximtop** [comment] 2023-08-21 08:41
Could you please check if the issue can be reproduced with a new version v4.2.151?

**Comment by mad-hin** [comment] 2023-08-21 08:56
Sorry I cannot check it since the version v4.2.151 was not available. I will update the status when it has been updated to 4.2.151

**Comment by maximtop** [comment] 2023-08-21 09:09
> Sorry I cannot check it since the version v4.2.151 was not available. I will update the status when it has been updated to 4.2.151

Oh, I see you're using Firefox. This version will be available for Firefox later.

**Comment by emikaadeo-git** [comment] 2023-08-23 09:26
Hi,
when we can expect version **4.2**.x to be available on [AMO](https://addons.mozilla.org/pl/firefox/addon/adguard-adblocker/) ?
4.2.151 was released two weeks ago.

**Comment by maximtop** [comment] 2023-08-23 09:34
Hi, @emikaadeo-git 

Thank you for your inquiry about version 4.2.x. I'm unable to provide an exact release date at this time. The next version for beta is currently under review, and while it was usually signed on the fly in the past, our deploy was not intended for this specific situation. We prefer not to publish the release before the beta is ready, and that's why we haven't released Firefox yet. Your patience is greatly appreciated.

**Comment by emikaadeo-git** [comment] 2023-08-24 15:27
@maximtop 
Thanks!
Looking forward for stable release on AMO.

**Comment by Birbber** [comment] 2023-09-21 08:21
@emikaadeo-git Hi! The latest version is already available in the store. 
I'm closing this issue, please re-open if needed.

**Closed by Birbber** 2023-09-21 08:21 UTC
Labels: Bug, Priority: P4
