### ISSUE TITLE
Opinion Stage blocked by mistake

### ISSUE THREAD

**Issue by aparag** [AdguardTeam/AdguardBrowserExtension#1870] opened 2021-09-30 12:34 UTC
Hi,
Adguard is blocking OpinionStage.com quiz & survey widgets. 
Opinion Stage is a SaaS model based service for creating interactive quizzes & surveys and not an ad related service.
Can you please remove the site/widgets from your blocking list,
Thanks!
Assaf

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Browser and version:**
  - 
- **Operating system and version:**
  - 
- **Filters you use in AdGuard:**
  - 
- **Stealth Mode settings:**
  - 
- **Other browser extensions:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

###

**Comment by Birbber** [comment] 2021-09-30 13:32
@aparag Hi!
Could you provide screenshots of such blocking?
Also specify what filters did you enable?

**Comment by aparag** [comment] 2021-09-30 13:42
Hi!
For example, take a look at this page:
https://blog.flypgs.com/karakterine-gore-deneyim-seyahati/
When the blocker is off, you can see a quiz widget.
When it is on (default settings), the quiz dissapears.
Let me know if you need more examples,
Thanks,
Assaf

**Comment by Birbber** [comment] 2021-09-30 13:54
@aparag AG doesn't block quiz widgets on these websites for me.
Please export your settings, so we could try to reproduce. Just click "Export settings" in general settings and send exported file here or to devteam@adguard.com.

**Comment by aparag** [comment] 2021-09-30 14:03
just sent you an email. Note that I didn't change the default settings after downloading/enabling the addon.

**Comment by Birbber** [comment] 2021-09-30 14:13
@aparag Thanks, just checked it. 
I had to make sure in case there were some language-specific filters enabled automatically.
Wierdly enough, I can see the widget even with AdGuard enabled, but it shows up with an insignificant delay.

What browser (specify browser version as well) and OS do you use?

**Comment by aparag** [comment] 2021-09-30 14:20
Chrome on Windows (from he about: Version 94.0.4606.61 (Official Build) (64-bit))

**Comment by Alex-302** [comment] 2021-09-30 14:23
@aparag Please send report using AdGuard. All necessary info will be filled automatically.

**Comment by aparag** [comment] 2021-09-30 14:25
how do I do that? don't see a report function in the chrome extension

**Comment by Alex-302** [comment] 2021-09-30 14:27
@aparag Described here: https://kb.adguard.com/en/technical-support/reporting-tool

Please post resulting link here.

**Comment by aparag** [comment] 2021-09-30 14:37
https://github.com/AdguardTeam/AdguardFilters/issues/96128

**Comment by aparag** [comment] 2021-10-03 09:40
they removed the widget from there, here is another site with a widget:
https://www.sammobile.com/quiz/weekly-sammobile-quiz-92-come-test-your-samsung-knowledge/
However it seems it is now displaying normally, so seems like issue is fixed from my end. Can you also verify you see the widget:
https://www.screencast.com/t/H1Miinj1nLy7
Thanks!
Assaf

**Comment by Birbber** [comment] 2021-10-04 10:23
@aparag Yes, the widget is visible both with AG on and off.

**Comment by Birbber** [comment] 2021-10-04 10:54
I'm closing the issue in this repository, since it was created [here](AdguardTeam/AdguardFilters#96128).

**Closed** 2021-10-04 10:55 UTC
