### ISSUE TITLE
Block Ads Selection doesn't work

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#277] opened 2016-06-23 14:35 UTC
[videos.zip](https://github.com/AdguardTeam/AdguardBrowserExtension/files/330163/videos.zip)

doesn't work on the laptop but works on desktop computer with the same setup

"I was able to confirm that the problem does not occur with version 2.2.4.
The problem definitely began with version 2.3.4. It also exists with 2.3.5
beta and 2.3.6 beta."

"I've tried disabling all other extensions. I've tired removing all other
extensions. I've uninstalled Chrome and done a fresh install. I've tired
different users. I've tired different profiles. The same versions of
Windows 10 and Chrome work as expected on my desktop. I've run
virus/malware scans, system file check scans, all the standard integrity
tests on my laptop, but no anomalies are detected."

please refer to customer id 1285759

**Comment by evgeniy-ADG** [comment] 2016-07-07 13:43
> FYI. Just sanitized my laptop drive, performed a clean Windows 10 install, installed Chrome, and installed Adguard. Absolutely no difference!

**Comment by Mizzick** [comment] 2016-07-08 16:16
What's the model of laptop?
I think the problem should be about different event on mouse click.

**Comment by ameshkov** [comment] 2016-07-10 16:13
Could it be that this is not a mouse click, but a touch event?

**Comment by claytoncarney** [comment] 2016-07-10 23:07
FYI. Dell Inspiron 3521. I suspect the problem centers around mouse hover event rather then click.

Sudden erratic system behavior observed (malware suspected). Had to reflash BIOS, sanitize drive, and clean install. Now Selection Mode is working normally. Apologies for the distraction. Until this had no reason to suspect system.

**Comment by claytoncarney** [comment] 2016-07-10 23:11
P.S. Appreciate the support. Adguard is without a doubt the best ad blocker available!

**Comment by claytoncarney** [comment] 2016-07-11 01:32
UPDATE: Appears the problem is somehow related to the touchscreen. For some reason, the touchscreen was disabled after the last install. That's why Adguard was working. Once I enabled the touchscreen, the problem returned (although somewhat erratically). I checked and the driver is up to date. I'll try uninstalling and reinstalling the driver.

**Comment by ameshkov** [comment] 2016-07-12 09:43
Let's summarize: there may be a problem selecting elements with a mouse click when touch screen is enabled, right?

I'll try to reproduce this on Yoga tablet, need some time to figure out how to plug mouse in:)

**Comment by claytoncarney** [comment] 2016-07-12 12:35
Not exactly. As demonstrated in the screencasts, the problem is that page
elements are not highlighted (and made available for selection) when the
cursor hovers over them.

But, yes, it is absolutely repeatable that the problem only occurs when the
touch screen is enabled.

**Comment by ameshkov** [comment] 2016-07-13 09:21
@Mizzick i've received one more bug report on this issue. Please take care of this as soon as possible.

**Comment by Mizzick** [comment] 2016-07-13 11:13
`(('ontouchstart' in window) || (navigator.msMaxTouchPoints > 0))`
Please check this in browser console. This can tell us if we check for touch events support properly.

**Comment by ameshkov** [comment] 2016-07-15 11:59
@claytoncarney to do the check:
1. Go to browser menu -> More tools -> Developer Tools
2. Switch to "Console" tab
3. Copy/paste command there: `(('ontouchstart' in window) || (navigator.msMaxTouchPoints > 0))` and press enter
4. Please tell us what is the output

**Comment by claytoncarney** [comment] 2016-07-15 12:51
> (('ontouchstart' in window) || (navigator.msMaxTouchPoints > 0))
> true

Specifically:

> ('ontouchstart' in window)
> true
> (navigator.msMaxTouchPoints > 0)
> false

**Comment by claytoncarney** [comment] 2016-07-15 13:04
More specifically:

> navigator.msMaxTouchPoints
< undefined
> window.ontouchstart
< null

**Comment by Mizzick** [comment] 2016-07-15 14:45
Ok, thanks!

Seems like we don't handle it properly.
Please follow the link below: https://rawgit.com/AdguardTeam/AdguardTeam.github.io/master/test/touch_selector_bookmarklet.html

In this special version we added some tests and forcibly blocked touch events support.

**Comment by cabban** [comment] 2016-07-15 16:45
@ameshkov  
![image](https://cloud.githubusercontent.com/assets/19514493/16881833/44c08d38-4abc-11e6-88f3-8ffd2dd38220.png)

**Comment by ameshkov** [comment] 2016-07-15 17:07
@cabban hm, try clicking on that link instead of dragging.

**Comment by cabban** [comment] 2016-07-15 17:09
![image](https://cloud.githubusercontent.com/assets/19514493/16882498/9bc5e3c8-4abf-11e6-982f-990c7d805ed5.png)

@ameshkov  like this ?

**Comment by cabban** [comment] 2016-07-16 09:34
@ameshkov its only working with touch now, i want to work like before with mouse also :)

**Comment by claytoncarney** [comment] 2016-07-17 01:38
Apologies for the delay. My touch screen is working intermittently lately...

Element selection with the mouse is working again. And tapping on an
element displays a rawgit.com says dialog.

**Comment by cabban** [comment] 2016-07-17 19:34
i cant get the mouse to block :/

**Comment by ameshkov** [comment] 2016-07-18 11:51
@cabban weird, @Mizzick said he had explicitly blocked touch support, not the mouse)
> In this special version we added some tests and forcibly blocked touch events support.

@Mizzick let's sort this out finally, I'd desperately want to get new beta version.

**Comment by Mizzick** [comment] 2016-07-18 11:58
https://rawgit.com/AdguardTeam/AdguardTeam.github.io/master/test/touch_selector_bookmarklet.html

So does it work from this version?
Please paste the console output.

**Comment by claytoncarney** [comment] 2016-07-18 13:07
test.mp4
<https://mega.nz/#!poJ0jCjQ!gM3FJpQbxOlZb3JBRpHPoRJMPcmjD9IF7V-4XqM2ulc>

**Comment by ameshkov** [comment] 2016-07-18 14:33
@claytoncarney this is mouse cursor on the video, right?

**Comment by claytoncarney** [comment] 2016-07-18 14:50
I'm alternatively using both the mouse and touch.

**Comment by Mizzick** [comment] 2016-07-18 16:17
Ok, fixed. Will be in the next beta.

**Closed by Mizzick** 2016-07-18 16:17 UTC
Labels: Bug, Chromium, Help wanted
