### ISSUE TITLE
Add "Check for Filter Updates" Button

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardBrowserExtension#2144] opened 2022-07-27 06:13 UTC
I am running the latest version - Yes
I checked the documentation and found no answer - Yes
I checked to make sure that this issue has not already been filed - Yes

### Problem Description
Currently, if I want to check for filter updates, I need to open the extension settings and navigate to the 'Filters' page and then click on 'Check for updates' button. Not really a problem.

Until now, one could right-click on the extension icon and check for filter updates via the context menu but that too has disappeared.

### Proposed Solution
It would be good if there is a button to check for updates directly when clicking on the extension icon

https://prnt.sc/adDU6G_d8oKX

### Alternatives Considered

The manual way of checking for filter updates as mentioned in the problem description.

**Comment by maximtop** [comment] 2022-07-27 06:22
Hi, 
This is a duplicate of this issue https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1455

**Closed by maximtop** 2022-07-27 06:22 UTC

**Comment by Nzzyme** [comment] 2022-07-27 07:45
Apologies. I searched with "Check for updates" and did not find it.
