### ISSUE TITLE
Fonts are tiny and thin

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#2180] opened 2022-08-29 16:57 UTC
### Issue Details

- **AdGuard version:**
  - AdGuard v4.1.19
- **Browser and version:**
  - Chrome 104
- **Operating system and version:**
  - Windows 10

v4.1.19
![4 1 9](https://user-images.githubusercontent.com/112417589/187254993-311af35d-5d04-4652-8531-2cb21c8de856.png)

v.4.0.204
![4 0 204](https://user-images.githubusercontent.com/112417589/187254566-a2ca9225-d611-436e-b8c5-efc924195830.png)

**Comment by gork7777** [comment] 2022-08-29 17:15
Duplicate of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2158

**Comment by Birbber** [comment] 2022-08-30 07:43
Yes, surely a duplicate of #2158. Closing this one.

**Closed by Birbber** 2022-08-30 07:43 UTC
