### ISSUE TITLE
Normalization of Font Family

### ISSUE THREAD

**Issue by hl2guide** [AdguardTeam/AdguardBrowserExtension#1729] opened 2020-12-10 03:41 UTC
### Expected Behavior

Same font regardless of browser.

### Actual Behavior

Very condensed font in Firefox, un-condensed in Edge Chromium.

### Screenshots

![example](https://user-images.githubusercontent.com/17044982/101718448-50af5b00-3af5-11eb-9bab-9e37ff3dedc8.JPG)

**Comment by Chinaski1** [comment] 2020-12-11 10:00
Hello @hl2guide 

Pretty weird behavior. Please, specify the following information:
- Version of FF browser;
- Version of AdGuard Extension;
- Did you try to simply reinstall the extension?

I was unable to reproduce the issue on [version 3.5.23](https://uploads.adguard.com/Chinaskiwc1g3.png)

**Comment by hl2guide** [comment] 2020-12-11 12:08
FF: 83.0 64-bit Windows
AdGuard Extension: Version 3.5.23

I'll try a reinstall in the next few days.

**Comment by Chinaski1** [comment] 2020-12-11 12:44
I think you can restart the browser first and check if the issue still persists.

**Comment by hl2guide** [comment] 2020-12-12 02:59
Issue continues after Firefox was restarted.

**Comment by Chinaski1** [comment] 2020-12-14 09:07
Please clarify are use any third-party extensions or any settings that change the styles in the browser?
Will the situation be the same if the browser is installed cleanly?

**Comment by Chinaski1** [comment] 2020-12-21 12:00
I am unable to reproduce this issue.
Since the user has stopped responding, I am closing the task.
Reopen it if the problem recurs.

**Closed** 2020-12-21 12:02 UTC
