### ISSUE TITLE
Unable to install Brave extension, error unzipping

### ISSUE THREAD

**Issue by sysfu** [AdguardTeam/AdguardBrowserExtension#2271] opened 2023-01-19 16:36 UTC
### AdGuard Extension version

4.1.53

### Browser version

Brave Version 1.46.153 Chromium: 108.0.5359.128 (Official Build) unknown (64-bit)

### OS version

Qubes 4.1.1 w/Debian GNU/Linux 11 VM

### Issue Details

Extension won't install, says 'could not unzip extension'

### Expected Behavior

Extension unzips and installs

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by mozartinio** [comment] 2023-01-25 11:31
@sysfu 
Hello!
Did you try to download extension via Chrome store?

**Comment by sysfu** [comment] 2023-01-26 19:01
> @sysfu Hello! Did you try to download extension via Chrome store?

Yes, and it fails with the unzip error. This is the URL I am downloading from https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg

**Comment by maximtop** [comment] 2023-01-27 10:06
@sysfu,

We have checked the extension installation on our Brave browser and it installed as expected. We recommend installing the extension from the store, disabling any browser extensions or antivirus software that may be blocking the extension, and ensuring that you have enough disk space. Additionally, we recommend checking for updates and support resources within the Brave browser. If the problem persists, we recommend contacting Brave support for further assistance.

**Comment by sysfu** [comment] 2023-01-27 15:36
> @sysfu,
> 
> We have checked the extension installation on our Brave browser and it installed as expected. We recommend installing the extension from the store, disabling any browser extensions or antivirus software that may be blocking the extension, and ensuring that you have enough disk space. Additionally, we recommend checking for updates and support resources within the Brave browser. If the problem persists, we recommend contacting Brave support for further assistance.

I think the issue I'm having might have to do with Qubes OS sandboxing, not sure. I installed Brave into a Qubes OS debian VM using flatpak. I have the latest version of Brave available in the flatpack repo. 

user@Brave-Browser:~$ flatpak list
Name           Application ID                Version  Branch      Installation
Brave Browser  com.brave.Browser             1.47.186 stable      user

Are you able to spin up a copy of Qubes OS, install Brave into a dedicated virtual machine, and see if you can reproduce the error?

If not, are there any logs in Brave that I can examine to determine exactly why the file is failing to unzip? Maybe it's permissions issue?

I will try to reproduce this error in a Standalone VM, that does not have the non-writable system directories.  https://www.qubes-os.org/doc/standalones-and-hvms/

**Comment by maximtop** [comment] 2023-01-27 16:21
If you'll find something, keep us notified, please.

**Comment by sysfu** [comment] 2023-01-27 18:33
> If you'll find something, keep us notified, please.

I created a new standalone VM, installed Brave using flatpak, and then tried to install both the regular Adguard extension and the beta version. Both failed to unzip.

**Comment by mozartinio** [comment] 2023-02-06 12:02
@sysfu 
We are not reproducing the problem in any way and can assume that the problem is on your side
I'll close the issue for now but if it happens again to someone else, we'll reopen the problem and start looking for the cause

**Closed by mozartinio** 2023-02-06 12:02 UTC
