### ISSUE TITLE
Adguard Blocks URL

### ISSUE THREAD

**Issue by ngdaniel1** [AdguardTeam/AdguardBrowserExtension#1525] opened 2019-11-13 07:24 UTC
https://www1.swatchseries.to/episode/the_mandalorian_s1_e1.html

I selected a link to vev.io and it brings me to a page that does not have a Click Here To Play button like it used to.  

When I turn off Adguard, the button returns but opens my browser to all the useless stuff.

The link is supposed to lead to https://vev.io/78r8pm1pm534

![Annotation 2019-11-13 022110](https://user-images.githubusercontent.com/30162872/68741784-86b1a100-05bc-11ea-9a3d-85cb582be250.jpg)

![Annotation 2019-11-13 022139](https://user-images.githubusercontent.com/30162872/68741795-8dd8af00-05bc-11ea-93d8-d67fb7de73ee.jpg)

![Annotation 2019-11-13 022214](https://user-images.githubusercontent.com/30162872/68741802-9204cc80-05bc-11ea-880a-6ba621aad935.jpg)

**Comment by AdamWr** [comment] 2019-11-13 09:12
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/43933
Please update filters.

**Closed by AdamWr** 2019-11-13 09:12 UTC
