### ISSUE TITLE
The Prebake filter link is compromised

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardBrowserExtension#1426] opened 2019-06-18 04:04 UTC
![image](https://user-images.githubusercontent.com/15856304/59652609-1cc0d700-9197-11e9-95d2-d4ee942572c7.png)

It leads to http://liamja.co.uk/Prebake/ then redirects several times and ends up [here](http://www.apple.com-shield-device.live/redirects/?ip=188.163.2.58&campid=a536db57-83a4-46d1-bb5d-b4b52e9ec1a1&zn=hotel-deb-SMQwuVVH&sc=f1be0f9b-24b9-4ef6-b115-1b6525e2d391&browser=Chrome&browserversion=Chrome%2075&city=Kiev&os=MacOS&osv=MacOS%2010.14%20Mojave&model=Desktop&td=tracking.marketing&ua=Mozilla%2F5.0%20%28Macintosh%3B%20Intel%20Mac%20OS%20X%2010_14_5%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F75.0.3770.90%20Safari%2F537.36&language=uk&connection=MOBILE&isp=Kyivstar&carrier=Kyivstar&country=UA&cep=s6i0cMFNlUhqnT-qvP7jSmEA5LvJgvfRkIU3OH0JIojpZDvmh_-qphCwkh9J_NjqnTjnPxNOeNcP3bpk1JLQ_MhiZxmEYaOXtwFCwzHBx-o0TkL5Hjr5Ano2r7XpIyft4jGHfK7C2VVDKNhu6Jwwk_-C85g4TMmNDOmuVPKcbGsN1yf4JM8ioT1CeDQMX4iMajkOQ7d_rFD_6GJi4mWIxTcpz96k-9dLtNdq23FI6hDkURsRvun7ZikwjVGQtkhj_eFAJshDHnkWxvhxnBvYhW-ACQ-uda_IPQssVqvxHRKnYp83NjKz87L7E3tID33CzxM6E9HLMIzXWKEOIy9jN-nJrhChM9m_YrMZbkMFUfTwPMtHVld8teGy_rztsZNjD8NGO5lGYO7JHY7NM0G-4Fz5O1rtmWUxSMjy5Vkuc6h1_cHw2x_TiQkuMrZVYTEbnVdn1N34sIpZ3Vr7jFyCdNjnMvG4hZqd0_BoW8fSEc3d6I9j9-DKBOhAh2jqJoOC0bvlP9d6lLLYmRmqtqzGUA)

![image](https://user-images.githubusercontent.com/15856304/59652653-4b3eb200-9197-11e9-8eb6-9c5b3d256fed.png)

**Comment by zzebrum** [comment] 2019-06-19 11:47
Should we remove the filter completely? @ameshkov

**Comment by zzebrum** [comment] 2019-07-26 14:21
ok, as I see the link is ok now. The issue will be fixed with the next update

**Comment by snhv** [comment] 2019-08-19 16:28
Why do you still keep a filter when it's already obsolete?

**Comment by ameshkov** [comment] 2019-08-21 19:43
@snhv that's a good question.

The problem is that we've never removed a filter list from FiltersRegistry because this was never properly tested. We need to check how different AG products handle this.

**Closed** 2019-10-23 10:36 UTC
Labels: Bug, P4: Low
