### ISSUE TITLE
Statistics graph not working

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardBrowserExtension#1241] opened 2019-01-03 09:45 UTC
See screenshot. It looks like only the current day is working. Maybe I missed some settings or anything like that. So if that's not a bug, any help is appreciated.

<details><summary>Screenshot:</summary>

![screenshot 2019-01-03 at 10 38 56](https://user-images.githubusercontent.com/10995998/50631403-6b114f00-0f44-11e9-9d1d-c5c036caa0de.png)

</details>

### Your environment
* AdGuard AdBlocker extension version: 3.0.3
* Environment name and version: Chrome 71.0.3578.85

**Comment by danidoedel** [comment] 2019-01-06 21:01
Well it was still 0 for the next day though... nothing changes for me...

**Comment by maximtop** [comment] 2019-02-08 09:52
@danidoedel I can't reproduce this issue. Do you confirm that you can still observe it?

**Comment by danidoedel** [comment] 2019-02-08 11:09
It seems to work now... at least for the current day. I can't see any stats for yesterday in the weekly overview though. My guess is that after an update the stats are reset?

**Comment by maximtop** [comment] 2019-02-08 11:42
Actually, they shouldn't unless you didn't remove the extension and then installed it again.

**Comment by maximtop** [comment] 2019-02-08 15:08
I'm closing this issue if you'll encounter with the problem again, feel free to create a new one

**Closed by maximtop** 2019-02-08 15:08 UTC
Labels: Bug, P4: Low
