### ISSUE TITLE
Browser crashes with AdGuard extension enabled

### ISSUE THREAD

**Issue by 2962152120** [AdguardTeam/AdguardBrowserExtension#2917] opened 2024-08-26 16:02 UTC
一天能奔个十几次。wowtab奔溃。看b站奔溃！！！
受不了！！！

**Comment by alexx7311** [comment] 2024-08-26 16:54
@2962152120 Hello! 
What browser and the extension version are you using? Have you tried disabling all other extensions except for AdGuard?

Please do the following if you're using Chrome: 
1. Quit any running instance of Chrome.
2. Right-click your Chrome shortcut.
3. Select **Properties**.
4. At the end of the **Target**: line, add the command line flags: `--enable-logging --v=1`
5. With that example flag, it should look like: `chrome.exe --enable-logging --v=1`
6. Click `Apply` and then `OK`.
7. Launch Chrome using your shortcut.
8. Reproduce the problem.

The file with debug logs will be stored in the user data directory as chrome_debug.log

Please also go to `Settings > General > Export settings`
Then attach the resulting files to the comment in this issue.

**Comment by Afreedbaig** [comment] 2024-08-26 17:08
> @2962152120 Hello! What browser and the extension version are you using? Have you tried disabling all other extensions except for AdGuard?
> 
> Please do the following if you're using Chrome:
> 
> 1. Quit any running instance of Chrome.
> 2. Right-click your Chrome shortcut.
> 3. Select **Properties**.
> 4. At the end of the **Target**: line, add the command line flags: `--enable-logging --v=1`
> 5. With that example flag, it should look like: `chrome.exe --enable-logging --v=1`
> 6. Click `Apply` and then `OK`.
> 7. Launch Chrome using your shortcut.
> 8. Reproduce the problem.
> 
> The file with debug logs will be stored in the user data directory as chrome_debug.log
> 
> Please also go to `Settings > General > Export settings` Then attach the resulting files to the comment in this issue.


it would have been better if you just translated it to this native language before sending but still I appreciate you effort though

so let me do it for you : 

你用的是什么浏览器和扩展版本？你试过禁用除AdGuard以外的所有扩展吗？

如果你使用的是Chrome，请执行以下操作：

退出所有正在运行的Chrome实例。
右键单击你的Chrome快捷方式。
选择“属性”。
在“目标”一行的末尾添加以下命令行标志：--enable-logging --v=1
添加后，它应该看起来像这样：chrome.exe --enable-logging --v=1
点击“应用”，然后点击“确定”。
使用你的快捷方式启动Chrome。
重现问题。
调试日志文件将保存在用户数据目录中，文件名为chrome_debug.log。
另外，请前往“设置” > “常规” > “导出设置”，然后将生成的文件附加到此问题的评论中

**Comment by alexx7311** [comment] 2024-09-03 08:45
@2962152120 We'll close the issue for now. Please leave a comment if the problem is still relevant.

我们将暂时关闭该问题。如果问题仍然存在，请留下评论。

**Closed** 2024-09-03 09:17 UTC
Labels: Waiting for repro, Priority: P4
