### ISSUE TITLE
Referrer hidden even when rule unblocks it

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardBrowserExtension#2648] opened 2023-12-14 19:46 UTC
### AdGuard Extension version

4.2.240

### Browser version

Chrome 120.0.6099.110

### OS version

Windows 11

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send websites signals not to track you, Self-destruction of third-party cookies, Hide Referrer from third parties, Remove X-Client-Data header, Disable WebRTC

### Issue Details

https://venushd.click/live/stream-21.php

This website shows error:
Referrer check failed, null referrer not allowed

This rule should disable every stealth option:
`@@||*.*$stealth,important`

When I manually disable referrer option in stealth option it works.
It also works when I block their script via this rule:
`||weblivehdplay.ru/blast.js`

### Expected Behavior

Rule disables every stealth mode

### Screenshots

<img width="420" alt="image" src="https://github.com/AdguardTeam/AdguardBrowserExtension/assets/34266271/b7e29f44-cbc6-406b-94ea-fa69de707ca1">

### Additional Information

You have to unblock the mentioned script file with rule (or disable base filter):
`@@||weblivehdplay.ru/blast.js`

**Comment by BlazDT** [comment] 2023-12-14 19:50
@AdamWr did you experience this issue in the past already?

**Comment by AdamWr** [comment] 2023-12-14 21:12
No, I didn't and I cannot reproduce it with version `4.2.228` (in Opera and Firefox).

As far as I can see, `4.2.240` is a new version - https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v4.2.240-beta, marked as beta, though in Chrome I have stable version installed and it's already updated to version `4.2.228`.
In changes there is `Remove referrer from the document.referrer` - https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1844, I'm not sure, but I suppose that it may be related to this issue.

I think that if there is an exclusion with `$stealth` modifier then `hideDocumentReferrer` function should be disabled.
https://github.com/AdguardTeam/tsurlfilter/blob/c0ea1cad19c2d45f99bb6ef0b58818fdfffe9ef8/packages/tswebextension/src/lib/common/stealth-helper.ts#L36-L50

**Comment by BlazDT** [comment] 2023-12-14 22:22
var _0x2c4597 = document.referrer;
  if (typeof _0x2c4597 === "undefined" || !_0x2c4597) {
    window.alert("Referrer check failed, null referrer not allowed");
    throw new Error("Referrer check failed");
  }

This part is causing the error on that site (i replace bgbody with window.alert). Though when I add a rule to show document.referrer in a window.alert it shows something.

ATM the site seems to be broken (jquery loading error even though file is loading). Still strange it worked with referrer option disabled.
Just checked the site without any adblockers and error was displayed too. So probably site issue and beta issue.

**Comment by Yuki2718** [comment] 2024-01-28 13:29
Same issue on `https://jra.webcdn.stream.ne.jp/web/jra/onetag2020/eqPcPlayer2.html?target=202401060711` (probably geo-restricted). Even `@@||stream.ne.jp^$stealth` doesn't work, I have to turn the feature off to make the player work.

**Comment by stanislav-atr** [comment] 2024-01-29 13:01
@Yuki2718, thanks for the str, what version is this? `@@||stream.ne.jp^$stealth` works fine on v4.3.10

**Closed** 2024-04-09 11:23 UTC
Labels: Bug, Resolution: Fixed, Status: Resolved, Version: AdGuard v4.3, Priority: P3
