### ISSUE TITLE
Search feature gets disabled

### ISSUE THREAD

**Issue by RayReddingtonx** [AdguardTeam/AdguardBrowserExtension#2788] opened 2024-04-16 13:00 UTC
### AdGuard Extension version

Version 4.3.46

### Browser version

Opera, latest

### OS version

Windows 10

### Issue Details

its not allowing to search anything on youtube, and sefaria.org. Means unknown number of sites lose search features when adguard is on. Theres no way to delete its cache or whatever like we have on UBlock

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment] 2024-04-16 15:52
@RayReddingtonx Hello! What do you mean by 'not allowing to search anything'?
What filters do you have enabled? Does the problem reproduce in Opera's incognito mode?

**Comment by alexx7311** [comment] 2024-04-22 12:21
@RayReddingtonx any updates?

**Comment by alexx7311** [comment] 2024-04-27 08:15
@RayReddingtonx We'll close the issue for now. You can leave a comment if the problem is still relevant.

**Closed** 2024-04-27 08:15 UTC
Labels: Bug, Priority: P4

**Comment by RayReddingtonx** [comment] 2024-04-27 10:09
sorry for late reply. I have checked everything by turning off all filters by trial, and eventually i think i caught it. Its the github block list that's blocking search from certain sites including Youtube, so i had to disable Adguard for those sites. This list 
 
Filter:
https://github.com/blocklistproject/Lists/blob/ec7f9a155ccf1e701f92a5c035dcdb7c7c18e02b/porn.txt
![Screenshot 2024-04-27 151958](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/87129806/e7513381-33d0-46af-800a-d1458c88de66)

f** this porn list. Such an annoyance.

**Comment by alexx7311** [comment] 2024-04-27 13:08
@RayReddingtonx 
We looked inside the filter, it won't work in our extension because we don't have support for the `0.0.0.0 example.com` format, our rules look like `||example.com^`

If you need this filter, but with the right format, you can try this one https://blocklistproject.github.io/Lists/adguard/porn-ags.txt
We found it at https://github.com/blocklistproject/Lists?tab=readme-ov-file#main-lists
