### ISSUE TITLE
Remove gaps between items

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardBrowserExtension#2264] opened 2023-01-11 11:42 UTC
### Issue Details

![Screenshot 2023-01-11 194003](https://user-images.githubusercontent.com/122447646/211797656-df49e10a-c637-4749-b973-933277620a87.png)

**Comment by mozartinio** [comment] 2023-01-12 09:18
@98365 
Hello!
Thank you for mention it!

**Comment by ZCK22** [comment] 2023-08-09 14:01
Any update on whether this will still be worked on?

**Comment by maximtop** [comment] 2023-08-10 08:35
Not fixed yet, but is planned.

**Comment by maximtop** [comment] 2023-08-28 10:23
Duplicate of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2198

**Closed** 2023-08-28 10:23 UTC
Labels: Feature Request, Resolution: Duplicate, Status: Resolved, Priority: P4
