### ISSUE TITLE
Phishing and Malware protection seems to outright break youtube, removes all features from site except video.

### ISSUE THREAD

**Issue by thanhtacles** [AdguardTeam/AdguardBrowserExtension#2127] opened 2022-06-06 00:53 UTC
![image](https://user-images.githubusercontent.com/64636310/172077955-39e71864-99e4-4b95-a61c-9276bc947047.png)
When this option is toggled on, youtube refuses to load anything on the website, other than the video. 

Here's an example of what you would see. Literally nothing loads at all. You can't scroll down anywhere. There is no title and no clickable option icons on the top right like there should be. 
![image](https://user-images.githubusercontent.com/64636310/172078017-234db517-e778-4ab0-a093-3f336445c75e.png)

**Comment by Birbber** [comment] 2022-06-28 12:07
@thanhtacles Hi! Are you sure it's AdGuard that causes it? I wasn't able to reproduce the issue.
As far as I can see on the screenshot you added traffic is filtered by Brave itself: https://uploads.adguard.com/annrgy_udfm4.png

**Comment by Birbber** [comment] 2022-07-19 07:33
@thanhtacles Any news?

**Comment by Birbber** [comment] 2022-07-25 12:58
Closing due to no reply. Re-open if needed.

**Closed** 2022-07-25 12:59 UTC
Labels: waiting for data
