### ISSUE TITLE
The rule with '$document,subdocument' applied to iframe, blocks whole page

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#2322] opened 2023-04-06 17:15 UTC
### AdGuard Extension version

4.1.55

### Browser version

Chrome 111

### OS version

Windows 10

### What filters do you have enabled?

AdGuard Base filter

### Steps to reproduce:

1. Add `||adguard.com/404$document,subdocument` to user filter
2. Open https://jsfiddle.net/nbmz5ofk/

### Actual behavior:

AdGuard blocks jsfiddle.net
Same with `$document,subdocument,popup` modifiers.

### Expected Behavior

Frame with `adguard.com/404` must be blocked.

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/8361299/230449354-8fddda20-8401-4e7c-8a2b-1e66d766b4b2.png)

</details>

**Comment by contribucious** [comment] 2023-04-06 18:15
:eyes: Confirmed, same here too (on `v4.1.53` using Firefox `111.0.1`).

@Alex-302 To me, looks like a duplicate of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2095, isn't it? 🙂

**Closed** 2023-04-06 20:08 UTC
Labels: Bug
