### ISSUE TITLE
Maximize the filtering log window

### ISSUE THREAD

**Issue by urvbcn88** [AdguardTeam/AdguardBrowserExtension#1963] opened 2022-01-30 04:09 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

Maximize the filtering log window

Filtering log window of the `4.0` beta version is not wide. It's a bit annoying.
I have a 15.6 inch laptop with 1366x768 resolution.

Current log window:
<details>
 <summary>Screenshot</summary>
 
![resim](https://user-images.githubusercontent.com/95632675/151686231-9d4565fc-f185-4bcb-b5ad-248da69b7eda.png)

</details>

So I have to manually expand the window every time when I open the filtering log. I use the filtering log very often during the day.

Maximize the log window a little bit like in version `3.6.17`
Like this:
<details>
 <summary>Screenshot</summary>
 
![resim](https://user-images.githubusercontent.com/95632675/151686242-c43dd1c7-481a-44d1-ac1d-9988da7cea34.png)

</details>

**Comment by gork7777** [comment] 2022-01-30 13:37
Persist filtering log size will be added next verison of the extension: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1125

**Comment by Birbber** [comment] 2022-01-31 09:59
Closing as a duplicate of [#1125](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1125).

**Closed** 2022-01-31 09:59 UTC
