### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by MoreOwO** [AdguardTeam/AdguardBrowserExtension#2393] opened 2023-07-07 13:42 UTC
### AdGuard Extension version

4.1.56

### Browser version

Firefox 115

### OS version

Windows 11

### What filters do you have enabled?

AdGuard Base filter, AdGuard French filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, Liste FR

### Issue Details

Adguard takes up more and more ram until browser become laggy and I need to restart to return to normal (or to kill process in the task manager). Don't seem to have a pattern to it, just sometimes it starts eating more and more memory. Sometimes going over 9GB of ram

### Expected Behavior

A light/medium memory usage.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment] 2023-07-10 15:02
Hello! We couldn't reproduce the problem.  How many tabs did you have open?  Do you have any other apps or extensions installed that work with the network or installed in the browser? Have you tried disabling them? 

If the problem recurs, please take a screenshot in the about:performance tab

**Comment by MoreOwO** [comment] 2023-07-10 15:29
It might be a bug due to my computer/my install of firefox, i'll come back to you if it occurs again

**Comment by alexx7311** [comment] 2023-07-11 09:22
We'll close the issue for now. If the problem recurs you can reopen it.

**Closed** 2023-07-11 09:23 UTC
Labels: Bug, Priority: P4
