### ISSUE TITLE
Firefox: cannot add filter subscription

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#28] opened 2015-09-17 17:19 UTC
Steps to reproduce:
1. Go to Adguard settings
2. Click "All filters"
3. Enable one filter
4. Press "Save changes"

Expected result:
Filter is added to the list

Result:
Filter is not added to the list until page refresh

**Comment by Mizzick** [comment] 2015-09-18 11:12
Cannot reproduce with
Adguard AdBlocker (Beta) 2.0.15
FireFox 40.0.3

**Comment by ameshkov** [comment] 2015-09-22 06:24
Not that simple. This problem is reproducible if it takes too much time to download that filter list (try with EasyList for instance).

**Comment by Mizzick** [comment] 2015-09-23 12:15
Fixed with showing loader during downloading.

**Closed** 2015-09-26 21:15 UTC
Labels: Bug, Firefox
