### ISSUE TITLE
Adguard occasionally fails to block ads on youtube, in firefox browser. This happens when a new window or tab opens.

### ISSUE THREAD

**Issue by Ksanbah** [AdguardTeam/AdguardBrowserExtension#3025] opened 2024-11-05 16:19 UTC

**Comment by lilmnm-kamikaze-** [comment] 2024-11-06 02:49
The same happens for me as well. Even with page reload and cache clearing the ad still happens unless i change to a new tab and try to watch that video again.
Also happens when you open firefox when it was on a youtube video.

**Comment by windwak3r** [comment] 2024-11-07 14:22
@Ksanbah @lilmnm-kamikaze- Hello! Do you have the exact steps to reproduce the problem? Please update filters in the extension, clear your browser cookies and check if the problem persists.

**Comment by alije123** [comment] 2024-11-07 23:51
Adguard automatically resets its settings and ads are not blocked. I have to import the settings file all the time.
Version 4.4.41. Firefox 133.0b5

**Comment by lilmnm-kamikaze-** [comment] 2024-11-08 03:36
@windwak3r Yes i have updated and cleared all cookies and even cache and temporary data as well as checked for filter updates.  For me, I have Firefox opening tabs i had open the last time it was open. 
So my steps to get this issue are 
1. Go to a youtube video and watch some of it. 
2. Then i close firefox or restart my PC and open firefox again and it loads the video again but this time there is an ad being displayed. 
This issue also happens with opening a new tab. So step 2 above can also be opening a new tab without closing firefox.
I noticed twice last night that on some long videos (20 minutes or more) the video would stop buffering and need a page reload and after the reload there would be an ad being shown.

This doesnt happen all the time besides when i turn my pc back on and open firefox when it was on a youtube video. That would always display an ad for when the page loads.


> Adguard automatically resets its settings and ads are not blocked. I have to import the settings file all the time. Version 4.4.41. Firefox 133.0b5

i dont think that is related to this issue as my setting dont get reset and ads are blocked on other sites.

**Comment by windwak3r** [comment] 2024-11-08 09:46
@alije123 This is a Firefox bug. You can help us solving it if you follow the steps from https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775#issuecomment-2036577871 and leave a comment with results in https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775.

Then you can just reinstall the extension which solves the problem.

**Comment by scrutinizer11** [comment] 2024-11-08 22:54
I second. Running AG in Firefox from v. 1xx way back to v. 6x on every Mac machine I own has ads sneaking in on the first click and repeated reloads of the URL.

https://github.com/user-attachments/assets/daa7af84-07a8-4759-852c-00f7a4e13428

**Comment by windwak3r** [comment] 2024-11-11 15:59
@scrutinizer11 Please update the filters, clear your browser cookies and check if the problem persists.

If it does please export your AdGuard extension settings and attach them to a comment and specify which browser version are you using.

**Comment by windwak3r** [comment] 2024-11-19 09:07
@scrutinizer11 @lilmnm-kamikaze- any updates?

**Comment by hamilton5** [comment] 2024-11-19 18:01
I've noticed all ads failing to block on normal videos for the last 48 hours or so. Firefox 132.0.2 (64-bit)
[adg_ext_settings_4.4.41_191124-125939.json](https://github.com/user-attachments/files/17819442/adg_ext_settings_4.4.41_191124-125939.json)

**Comment by hamilton5** [comment] 2024-11-19 18:09
I've noticed all ads failing to block on normal videos for the last 48 hours or so. Firefox 132.0.2 (64-bit)
have tried the clearing site data/cookies, refresh, and relogin

[adg_ext_settings_4.4.41_191124-125939.json](https://github.com/user-attachments/files/17819506/adg_ext_settings_4.4.41_191124-125939.json)

**Comment by windwak3r** [comment] 2024-12-02 14:39
@scrutinizer11 @lilmnm-kamikaze- we'll close the issue for now. Please leave a comment if the problem is still relevant.

**Closed as completed** 2024-12-02 14:40 UTC
Labels: Waiting for repro, Resolution: Cannot Reproduce, Status: Closed, Priority: P4

**Comment by lilmnm-kamikaze-** [comment] 2024-12-10 04:03
Sorry it has been crunch time at work and lived there for the last few weeks. I will be home soon and will update on any changes.
