### ISSUE TITLE
All filters are turned off every time I restart the browser

### ISSUE THREAD

**Issue by msolomianiuk** [AdguardTeam/AdguardBrowserExtension#2744] opened 2024-03-15 20:12 UTC
### AdGuard Extension version

4.3.13

### Browser version

firefox 123.0.1

### OS version

windows 11

### Screenshots

<details><summary>Screenshot 1:</summary>

https://streamable.com/9v8it3

</details>

**Comment by msolomianiuk** [comment] 2024-03-15 20:19
https://github.com/AdguardTeam/AdguardBrowserExtension/assets/11045460/1809d0b3-ad98-40f9-8063-90ad3bee66aa

**Comment by MapoMagpie** [comment] 2024-03-16 06:54
me too.

But i installed the version 4.3.31 from [here](https://agrd.io/extension_firefox_beta)   ([releases](https://github.com/AdguardTeam/AdguardBrowserExtension/releases) > How to install beta:), this problem has never occurred.

Maybe it has been fixed in the new version or by simply reinstalling

**Comment by alexx7311** [comment] 2024-03-20 09:05
@msolomianiuk Hello! Looks like a duplicate of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2426
Please email [mtopciu@adguard.com](mailto:mtopciu@adguard.com) and mention this issue number in the subject (2744).

**Comment by akirichua** [comment] 2024-03-20 18:31
> Maybe it has been fixed in the new version or by simply reinstalling

There is an autorenew of extensions from addons.mozilla.org. But neither new updates, nor reinstall not helped.

**Comment by alexx7311** [comment] 2024-03-29 15:37
@akirichua Hello! This problem is most likely related to a [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1885297#c4). It would be great if you could help us debug this problem. We've outlined step by step everything that will need to be done. Link: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2755#issuecomment-2024912925

**Comment by alexx7311** [comment] 2024-04-04 08:41
@msolomianiuk @akirichua @MapoMagpie Hello! Further discussion will be in https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2775
If you would like to help us solve the problem, please leave a comment in that issue.

**Closed** 2024-04-04 08:42 UTC
Labels: Bug, Priority: P4
