### ISSUE TITLE
All filters are disabled after restarting browser

### ISSUE THREAD

**Issue by TheCheddarCheese** [AdguardTeam/AdguardBrowserExtension#2520] opened 2023-10-04 06:11 UTC
### AdGuard Extension version

4.2.168

### Browser version

Firefox 118.0

### OS version

Fedora Linux 38 Workstation

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, Dandelion Sprout's Nordic Filters

### Issue Details

When I close the browser or the system, all of the filters are disabled on start and I have to reenable them manually. This doesn't happen on any of my other systems.

### Expected Behavior

For the filter options to be saved and restored when the browser starts upd

### Screenshots

<details><summary>Screenshot 1:</summary>

![billede](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/124603704/7cd8c390-43cd-4fcf-bb8a-7440ab8ecce6)

</details>

**Comment by Birbber** [comment] 2023-10-05 11:46
Closing as a duplicate of #2517.

**Closed** 2023-10-05 11:47 UTC
Labels: Bug, Priority: P4
