### ISSUE TITLE
When exiting from browser AdGuard extension looses filters settings and white list

### ISSUE THREAD

**Issue by salvatore28** [AdguardTeam/AdguardBrowserExtension#2551] opened 2023-10-20 13:54 UTC
### AdGuard Extension version

4.2.189

### Browser version

Firefox 118.0.2

### OS version

Windows 10 22H2 build 19045.3570
Windows Feature Experience Pack 1000.19052.1000.0

### What filters do you have enabled?

AdGuard Base filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Other Annoyances filter, EasyList Italy, Fanboy's Annoyances, Web Annoyances Ultralist, Adblock Warning Removal List, I don't care about cookies

### What Stealth Mode options do you have enabled?

NONE

### Issue Details

Any time I close the browser, AdGuard filters settings and white list are lost and I have to reload them from a backup.

AG1 to AG4 are the settings as they appear after loading them from a backup.

After closing-reopening browser AG1 to After closing-reopening browser AG4 are the same pages after closing and reopening the browser.

### Expected Behavior

Settings MUST be retained.

### Screenshots

<details><summary>

Screenshot 1:
![AG1](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/3659039/edb893bd-fb8f-49b3-8b38-1c24d8b9edaa)

Screenshot 2:
![AG2](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/3659039/30b34856-1684-4377-b425-172d6f3bdcbe)

Screenshot 3:
![AG3](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/3659039/214177e6-ad55-4a67-8380-c645178ab87d)

Screenshot 4:
![AG4](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/3659039/27f4ef0e-4f00-4993-a110-f5cc7ab06098)

Screenshot 5:
![After closing-reopening browser AG1](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/3659039/7e28f3a3-8c4b-460d-be28-7577ccb71e7d)

Screenshot 6:
![After closing-reopening browser AG2](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/3659039/87ace571-b26f-4e6f-9f95-5399acbb9129)

Screenshot 7:
![After closing-reopening browser AG3](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/3659039/2eda033f-4e7d-48ea-a99f-46b7eeb6a08b)

Screenshot 8:
![After closing-reopening browser AG4](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/3659039/1c6477ea-f9e6-4150-be12-84369733908c)

</summary>

</details>

**Comment by alexx7311** [comment] 2023-10-27 13:33
@salvatore28 Hello! Please check if the problem persists on the latest beta build for FF at https://agrd.io/extension_firefox_beta

**Comment by LeKripiY** [comment] 2023-10-28 09:01
I also had this issue, and it seems that it is fixed for now with the lastest beta build 4.2.208, thank you

**Comment by alexx7311** [comment] 2023-11-07 10:40
@salvatore28 Did updating the extension solve the problem?

**Comment by alexx7311** [comment] 2023-11-13 09:37
@salvatore28 Maybe it was some local problem, we couldn't reproduce it. We will close the issue for now, if the problem happens again, please reopen the issue.

**Closed** 2023-11-13 09:38 UTC
Labels: Bug, Priority: P4
