### ISSUE TITLE
Some sites are broken by $$ rules in Firefox Quantum

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardBrowserExtension#1001] opened 2018-04-16 13:56 UTC
* ### kinopoisk.ru

Actual behavior - blank screen:

<details>

![image](https://user-images.githubusercontent.com/8361299/38813174-f4928874-4196-11e8-81e0-4f39a5afc514.png)

</details>

Caused by:
`kinopoisk.ru$$style[id="branding-style"]`
this rule is disabled for Firefox

Original issue: https://github.com/AdguardTeam/AdguardFilters/issues/13309#issuecomment-380697313

* ### Yandex Maps 
https://yandex.ru/maps/213/moscow/?l=trf%2Ctrfe

Actual behavior - blank screen:

<details>

![image](https://camo.githubusercontent.com/7b7e9eff50aa6afaecff8d80187569c79c208301/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f68374253546a4d2e706e67)

</details>

Caused by:
`://yandex.*/maps/$replace=/\,"adverts":\[.+?]}/\,"adverts":\[]\}/,important`
this rule is disabled for Firefox

Original issue: https://github.com/AdguardTeam/AdguardFilters/issues/14623#issuecomment-381836175

**Comment by vbagirov** [comment] 2018-04-18 15:33
* ### gazeta.ru

Actual behavior - blank screen:

Caused by:
`rns.online,championat.com,gazeta.ru,lenta.ru,rambler.ru$$script[tag-content="AntiAdBlock"][min-length="5000"][max-length="350000"]`
this rule is disabled for Firefox

Original issue: https://forum.adguard.com/index.php?threads/28496/#post-167071

**Comment by ameshkov** [comment] 2018-05-04 10:36
Fixed by `feature/issues/1001-encoding `

**Closed** 2018-08-13 14:41 UTC
Labels: Bug, Firefox
