### ISSUE TITLE
Removing filter subscription

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardBrowserExtension#524] opened 2017-01-23 13:25 UTC
Current way of complete subscription removal is unclear to user. 

You have to open "all filters" and save changes in that menu. 
In this case some filters that are temporary disabled will also be deleted even if user wanted to keep them in subscription list.

**Comment by ameshkov** [comment] 2017-01-26 09:51
The issue is resolved in the new design, let's just wait until it is implemented.

**Closed by ameshkov** 2017-01-26 09:51 UTC
Labels: Enhancement
