### ISSUE TITLE
Compatibility issue with Random Agent Spoofer add-on

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardBrowserExtension#174] opened 2016-02-23 22:41 UTC
![fc0xyq1](https://cloud.githubusercontent.com/assets/5947035/13269235/c6f9d07e-da97-11e5-9ce6-13ea9f2312fd.png)

**Comment by ameshkov** [comment] 2016-02-23 22:44
Please check it, the issue is major.

**Comment by Mizzick** [comment] 2016-02-24 14:14
Cannot reproduce with latest FF 44.0.2 and adguard 2.1.5.

**Comment by ameshkov** [comment] 2016-02-25 10:10
> Cannot reproduce with latest FF 44.0.2 and adguard 2.1.5.

So what? You must not close issues if you cannot reproduce anything.

Search for what can possibly cause this.

**Comment by ameshkov** [comment] 2016-02-25 10:14
Here is an update: translation is broken by RAS addon.

Please check it with a new version (based on frame scripts) which is in pull request now.

**Comment by Mizzick** [comment] 2016-02-27 12:44
Fixed with frame-scripts version #138

**Closed** 2016-02-29 14:33 UTC
Labels: Bug, Compatibility, Firefox
