### ISSUE TITLE
[Firefox] The blocking feature for custom ads does not work correctly

### ISSUE THREAD

**Issue by pro100Hub** [AdguardTeam/AdguardBrowserExtension#925] opened 2017-12-23 10:18 UTC
Hi!
If you try to lock the required tables, the control window disappears. This error manifests itself almost everywhere. You can try the problem [here](https://nnm-club.name/forum/viewtopic.php?t=1193606).
[Visual demonstration](https://i.imgur.com/FXwxt6K.gifv)

* AdGuard 2.8.1beta
* Firefox 56.0.2 (x64)

Regards.

**Comment by ameshkov** [comment] 2018-01-02 21:09
Yep, duplicate of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/671

Seems to be a browser bug triggered by the Assistant's UI (it's embedded inside of an iframe and dragging an empty link somehow makes iframe navigate to that empty link url).

**Closed by ameshkov** 2018-01-02 21:09 UTC
